/* ==================================================================
   Academic & Intellectual — reading, reasoning, mathematics, and the
   machinery of producing knowledge.
================================================================== */

addSkills({ cat: 'academic', group: 'Literacy' }, [
  { id:'read-fluency', name:'Reading Fluency', tier:1,
    desc:'Read continuous prose smoothly and at a comfortable pace without decoding effort.' },
  { id:'handwriting', name:'Handwriting', tier:1,
    desc:'Write legibly and fast enough that the pen keeps up with the thought.' },
  { id:'notetaking', name:'Note-Taking', tier:1,
    desc:'Capture the substance of a lecture, book or meeting in your own words.' },
  { id:'questioning', name:'Curiosity & Question-Asking', tier:1,
    desc:'Notice what you do not understand and turn it into a specific question.' },
  { id:'vocabulary', name:'Vocabulary Building', tier:2, req:['read-fluency'],
    desc:'Acquire words deliberately, including the ones that let you make finer distinctions.' },
  { id:'comprehension', name:'Reading Comprehension', tier:2, req:['read-fluency'],
    desc:'Extract the argument, evidence and structure from a text, not just the words.' },
  { id:'speed-reading', name:'Reading at Speed', tier:3, req:['comprehension','vocabulary'],
    desc:'Skim, scan and triage a stack of material, then slow down where it matters.' },
  { id:'close-reading', name:'Close Reading', tier:3, req:['comprehension'],
    desc:'Work a paragraph line by line for what it says, implies and quietly assumes.' },
  { id:'marginalia', name:'Reading With a Pen', tier:3, req:['close-reading','notetaking'],
    desc:'Annotate, argue with and index a book so it stays useful five years later.' },
  { id:'literature-reading', name:'Reading Literature', tier:4, req:['close-reading','historical-context'],
    desc:'Read a novel or poem for form, tradition and effect, not only plot.' },
]);

addSkills({ cat: 'academic', group: 'Mathematics' }, [
  { id:'numeracy', name:'Basic Numeracy', tier:1,
    desc:'Arithmetic, fractions, percentages and estimating answers in your head.' },
  { id:'mental-maths', name:'Mental Arithmetic', tier:2, req:['numeracy'],
    desc:'Do the sum in your head fast enough to catch a wrong number in conversation.' },
  { id:'estimation', name:'Estimation & Fermi Problems', tier:2, req:['numeracy'],
    desc:'Get within an order of magnitude on anything, from first principles, in a minute.' },
  { id:'algebra', name:'Algebraic Thinking', tier:2, req:['numeracy'],
    desc:'Work with unknowns, equations, functions and graphs.' },
  { id:'geometry', name:'Geometry & Trigonometry', tier:3, req:['algebra'],
    desc:'Shape, angle, distance and the trig that makes surveying and physics possible.' },
  { id:'statistics', name:'Statistics & Probability', tier:3, req:['algebra'],
    desc:'Distributions, uncertainty, correlation vs. causation, reading a study honestly.' },
  { id:'discrete-maths', name:'Discrete Mathematics', tier:3, req:['algebra','logic-basics'],
    desc:'Sets, graphs, combinatorics and induction — the maths computing runs on.' },
  { id:'calculus', name:'Calculus & Modelling', tier:4, req:['algebra','statistics'],
    desc:'Rates of change, accumulation, and expressing a real system as equations.' },
  { id:'linear-algebra', name:'Linear Algebra', tier:4, req:['algebra','geometry'],
    desc:'Vectors, matrices and transformations — the language of graphics and learning.' },
  { id:'bayesian', name:'Bayesian Reasoning', tier:4, req:['statistics','probabilistic-thinking'],
    desc:'Priors, likelihoods and updating, applied to real evidence rather than urns.' },
  { id:'proof', name:'Mathematical Proof', tier:4, req:['discrete-maths','logic'],
    desc:'Construct and check a rigorous argument that a thing must be true.' },
  { id:'analysis', name:'Real Analysis & Rigour', tier:5, req:['proof','calculus'],
    desc:'Limits, continuity and convergence done properly — where calculus becomes maths.' },
  { id:'applied-modelling', name:'Mathematical Modelling', tier:5, req:['calculus','linear-algebra','systems-thinking'],
    desc:'Turn a messy real system into equations that predict something checkable.' },
]);

addSkills({ cat: 'academic', group: 'Reasoning' }, [
  { id:'logic-basics', name:'Everyday Logic', tier:2, req:['questioning'],
    desc:'If–then, necessary and sufficient, and spotting a non-sequitur in conversation.' },
  { id:'critical-reading', name:'Critical Analysis', tier:3, req:['comprehension','source-search'],
    desc:'Test claims: spot assumptions, weak evidence, and motivated reasoning.' },
  { id:'fallacies', name:'Spotting Fallacies', tier:3, req:['logic-basics','critical-reading'],
    desc:'Name what is wrong with an argument precisely enough to answer it.' },
  { id:'steelmanning', name:'Steelmanning', tier:4, req:['fallacies','humility'],
    desc:'State the strongest version of a view you reject, to its holder’s satisfaction.' },
  { id:'logic', name:'Formal Logic & Argumentation', tier:4, req:['critical-reading'],
    desc:'Validity, inference, formal fallacies, and constructing airtight arguments.' },
  { id:'epistemology', name:'Epistemic Hygiene', tier:5, req:['logic','bayesian','humility'],
    desc:'Track how you know what you know, and how confident that actually licenses being.' },
  { id:'dialectic', name:'Dialectic & Disputation', tier:5, req:['steelmanning','logic','debate'],
    desc:'Reason with an opponent toward a better answer than either of you started with.' },
]);

addSkills({ cat: 'academic', group: 'Research' }, [
  { id:'source-search', name:'Finding Sources', tier:2, req:['read-fluency','questioning'],
    desc:'Locate books, papers and data that answer a question, and judge their quality.' },
  { id:'library-skills', name:'Library & Archive Skills', tier:2, req:['source-search'],
    desc:'Catalogues, interlibrary loan, special collections and asking a librarian well.' },
  { id:'literature-review', name:'Literature Review', tier:4, req:['source-search','critical-reading','notetaking'],
    desc:'Map what a field already knows, and where the argument is actually live.' },
  { id:'scientific-method', name:'Scientific Method', tier:3, req:['questioning','statistics'],
    desc:'Turn a curiosity into a falsifiable hypothesis and a test that could refute it.' },
  { id:'research-design', name:'Research Design', tier:4, req:['scientific-method','statistics'],
    desc:'Choose methods, controls and sample sizes that can actually answer the question.' },
  { id:'qualitative-methods', name:'Qualitative Methods', tier:4, req:['interviewing','research-design'],
    desc:'Interviews, coding and ethnography done with the rigour their critics assume is missing.' },
  { id:'research-ethics', name:'Research Ethics', tier:4, req:['research-design','integrity'],
    desc:'Consent, harm, data protection and the review process, treated as more than a form.' },
  { id:'reproducibility', name:'Reproducible Research', tier:5, req:['research-design','version-control','data-analysis'],
    desc:'Pre-registration, open data and code that lets someone else get your numbers.' },
  { id:'thesis', name:'Original Research', tier:5, req:['research-design','academic-writing'],
    desc:'Carry a novel question from design through analysis to a defensible written result.' },
  { id:'peer-review', name:'Peer Review & Critique', tier:5, req:['academic-writing','logic'],
    desc:'Evaluate someone else’s work rigorously and give a fair, useful verdict.' },
  { id:'grant-writing', name:'Grant Writing', tier:5, req:['academic-writing','persuasive-writing','budgeting'],
    desc:'Make a case for money for work that does not exist yet, on their terms.' },
]);

addSkills({ cat: 'academic', group: 'Writing' }, [
  { id:'sentence-craft', name:'Writing a Clear Sentence', tier:2, req:['read-fluency','vocabulary'],
    desc:'Subject, verb, object; cut the rest. The single highest-leverage writing skill.' },
  { id:'paragraphing', name:'Structuring a Paragraph', tier:2, req:['sentence-craft'],
    desc:'One idea, stated, supported, and handed to the next paragraph.' },
  { id:'essay-writing', name:'Essay Writing', tier:3, req:['comprehension','notetaking'],
    desc:'Build a thesis, support it in ordered paragraphs, and land a conclusion.' },
  { id:'editing', name:'Editing & Revision', tier:3, req:['paragraphing','essay-writing'],
    desc:'Cut a draft by a third and make it better; separate revising from proofreading.' },
  { id:'summarising', name:'Summarising', tier:3, req:['comprehension','sentence-craft'],
    desc:'Compress a long argument to a paragraph without losing what makes it true.' },
  { id:'persuasive-writing', name:'Persuasive Writing', tier:4, req:['essay-writing','fallacies'],
    desc:'Write to change a specific reader’s mind, anticipating their objections.' },
  { id:'academic-writing', name:'Academic Writing & Citation', tier:4, req:['essay-writing','critical-reading'],
    desc:'Write for a scholarly audience: literature review, method, citation discipline.' },
  { id:'technical-writing', name:'Technical Writing', tier:4, req:['editing','summarising'],
    desc:'Documentation and procedures a stranger can follow without asking you anything.' },
  { id:'prose-style', name:'Prose Style', tier:4, req:['editing','literature-reading','persuasive-writing'],
    desc:'Rhythm, register and voice — writing that is a pleasure as well as clear.' },
]);

addSkills({ cat: 'academic', group: 'Humanities' }, [
  { id:'historical-context', name:'Historical Thinking', tier:3, req:['comprehension','source-search'],
    desc:'Place events in their period and resist judging the past by today’s furniture.' },
  { id:'primary-sources', name:'Working With Primary Sources', tier:4, req:['historical-context','library-skills'],
    desc:'Read a letter, ledger or census return for what it can and cannot tell you.' },
  { id:'philosophy-history', name:'History of Ideas', tier:4, req:['historical-context','philosophy-of-life'],
    desc:'Trace where a concept came from and what problem it was invented to solve.' },
  { id:'art-history', name:'Art History', tier:3, req:['historical-context','visual-literacy'],
    desc:'Place a work in its movement, materials and market, and say why it mattered.' },
  { id:'geography-literacy', name:'Geographic Literacy', tier:2, req:['read-fluency'],
    desc:'Where places are, what they trade, and how terrain shaped who lives there.' },
  { id:'economics-literacy', name:'Economic Literacy', tier:3, req:['statistics','geography-literacy'],
    desc:'Supply, demand, inflation, trade-offs and reading an economic headline critically.' },
  { id:'anthropology', name:'Cultural Analysis', tier:4, req:['qualitative-methods','cultural-awareness'],
    desc:'See a practice from inside its own logic before evaluating it from outside.' },
  { id:'interdisciplinary', name:'Working Across Disciplines', tier:5, req:['literature-review','anthropology','systems-thinking'],
    desc:'Borrow a method from one field and apply it honestly in another.' },
]);

addSkills({ cat: 'academic', group: 'Philosophy' }, [
  { id:'philosophy-basics', name:'Philosophical Reading', tier:3, req:['close-reading','logic-basics'],
    desc:'Follow an argument across a chapter and identify the premise you would reject.' },
  { id:'ethics-theory', name:'Ethical Theory', tier:4, req:['philosophy-basics','logic'],
    desc:'Consequentialism, deontology and virtue ethics as tools rather than teams.' },
  { id:'political-philosophy', name:'Political Philosophy', tier:4, req:['philosophy-basics','civics-basics'],
    desc:'Liberty, justice, legitimacy and the arguments underneath every policy fight.' },
  { id:'philosophy-of-mind', name:'Philosophy of Mind', tier:5, req:['philosophy-basics','neuroscience'],
    desc:'Consciousness, intentionality and personal identity, taken seriously.' },
  { id:'philosophy-of-science', name:'Philosophy of Science', tier:5, req:['philosophy-basics','scientific-method'],
    desc:'Demarcation, underdetermination and what scientific evidence can actually establish.' },
  { id:'aesthetics', name:'Aesthetics', tier:4, req:['philosophy-basics','art-critique'],
    desc:'What makes something good, and whether that claim can be more than preference.' },
]);

addSkills({ cat: 'academic', group: 'Classics & Deep Reading' }, [
  { id:'canon-reading', name:'Reading the Difficult Books', tier:4, req:['close-reading','marginalia'],
    desc:'Work through a demanding primary text over weeks without secondary crutches.' },
  { id:'ancient-languages', name:'Ancient Languages', tier:5, req:['l2-grammar','etymology'],
    desc:'Latin, Greek, Sanskrit or Hebrew read slowly and properly with a lexicon.' },
  { id:'textual-criticism', name:'Textual Criticism', tier:5, req:['primary-sources','ancient-languages'],
    desc:'Manuscripts, variants and reconstructing what a text most likely said.' },
  { id:'commonplace', name:'Keeping a Commonplace Book', tier:4, req:['marginalia','note-systems'],
    desc:'Collect and index passages so a decade of reading stays available to you.' },
  { id:'reading-plan', name:'A Reading Programme', tier:4, req:['canon-reading','self-directed'],
    desc:'Sequence a field’s literature so each book makes the next one easier.' },
]);

addSkills({ cat: 'academic', group: 'Quantitative Methods' }, [
  { id:'hypothesis-testing', name:'Hypothesis Testing', tier:4, req:['statistics','research-design'],
    desc:'Power, p-values and what a significant result does and does not license.' },
  { id:'regression', name:'Regression Analysis', tier:4, req:['statistics','linear-algebra'],
    desc:'Fit, interpret and check a model, including the assumptions everyone skips.' },
  { id:'causal-inference', name:'Causal Inference', tier:5, req:['regression','research-design'],
    desc:'Instruments, controls and natural experiments — getting from correlation to cause.' },
  { id:'survey-design', name:'Survey Design', tier:4, req:['research-design','qualitative-methods'],
    desc:'Question wording, sampling and non-response that will not manufacture your answer.' },
  { id:'meta-analysis', name:'Meta-Analysis', tier:5, req:['hypothesis-testing','literature-review'],
    desc:'Pool studies properly, and detect publication bias rather than averaging it in.' },
  { id:'simulation', name:'Simulation & Monte Carlo', tier:5, req:['programming-basics','statistics'],
    desc:'Model uncertainty by running it ten thousand times instead of solving it.' },
]);

addSkills({ cat: 'academic', group: 'Academic Life' }, [
  { id:'conference-presenting', name:'Presenting at a Conference', tier:5, req:['academic-writing','presentations'],
    desc:'Twelve minutes and a hostile question, in front of the people you cite.' },
  { id:'academic-collaboration', name:'Collaborating on Research', tier:5, req:['thesis','collaboration'],
    desc:'Authorship, division of labour and data sharing agreed before the work starts.' },
  { id:'supervision', name:'Supervising Researchers', tier:5, req:['thesis','mentoring'],
    desc:'Guide someone else’s project without taking it over or abandoning them.' },
  { id:'science-communication', name:'Science Communication', tier:5, req:['explaining','summarising','peer-review'],
    desc:'Make real research intelligible to non-specialists without making it false.' },
]);

addSkills({ cat: 'academic', group: 'Everyday Intellect' }, [
  { id:'reading-habit', name:'A Reading Habit', tier:2, req:['read-fluency','habits'],
    desc:'Read books consistently, on purpose, in a world designed to prevent it.' },
  { id:'general-knowledge', name:'Building General Knowledge', tier:3, req:['reading-habit','memory-technique'],
    desc:'Broad shallow coverage that lets you place almost any new thing you meet.' },
  { id:'intellectual-honesty', name:'Intellectual Honesty', tier:3, req:['self-honesty','fallacies'],
    desc:'State the strength of your evidence accurately, including when it is weak.' },
  { id:'changing-your-mind', name:'Changing Your Mind', tier:4, req:['intellectual-honesty','humility'],
    desc:'Say publicly that you were wrong, cite what changed it, and move on.' },
  { id:'note-to-argument', name:'From Notes to an Argument', tier:4, req:['note-systems','essay-writing'],
    desc:'Turn a year of scattered reading into one thing worth someone else’s time.' },
  { id:'reading-across-disagreement', name:'Reading People You Disagree With', tier:4, req:['steelmanning','reading-habit'],
    desc:'Read the best of the other side, in their own words, at their strongest.' },
]);

addSkills({ cat: 'academic', group: 'Applied Numeracy' }, [
  { id:'percentages', name:'Percentages in the Wild', tier:2, req:['numeracy'],
    desc:'Increases, decreases, VAT and interest done right and checked for plausibility.' },
  { id:'reading-graphs', name:'Reading Charts Critically', tier:2, req:['numeracy','visual-literacy'],
    desc:'Axes, baselines and scales — spotting a chart designed to mislead.' },
  { id:'risk-numbers', name:'Understanding Risk Numbers', tier:3, req:['statistics','percentages'],
    desc:'Absolute vs. relative risk, and what a doubled tiny risk actually means.' },
  { id:'unit-pricing', name:'Comparing on Numbers', tier:2, req:['percentages','price-awareness'],
    desc:'Cost per unit, per use and per year, worked out at the shelf.' },
  { id:'back-of-envelope', name:'Back-of-Envelope Checks', tier:3, req:['estimation','mental-maths'],
    desc:'Sanity-check any claim, quote or plan in under a minute.' },
  { id:'compound-thinking', name:'Thinking in Compounding', tier:3, req:['percentages','estimation'],
    desc:'Growth, debt and habit modelled over years rather than intuited over days.' },
]);
