/* ==================================================================
   Business & Enterprise — turning capability into an offer, and an
   offer into something that keeps running.
================================================================== */

addSkills({ cat: 'business', group: 'Finding the Thing' }, [
  { id:'problem-spotting', name:'Spotting a Real Problem', tier:3, req:['questioning','observation'],
    desc:'Notice what people already work around, pay for badly, or complain about twice.' },
  { id:'customer-interviews', name:'Customer Discovery', tier:4, req:['interviewing','problem-spotting'],
    desc:'Ask about past behaviour rather than future intentions, and hear the no.' },
  { id:'market-sizing', name:'Market Sizing', tier:4, req:['estimation','data-analysis'],
    desc:'Work out from the bottom up how many buyers exist and what they already spend.' },
  { id:'competitor-analysis', name:'Competitor Analysis', tier:4, req:['market-sizing','critical-reading'],
    desc:'Map the alternatives, including doing nothing, and find the gap that is real.' },
  { id:'value-proposition', name:'Value Proposition', tier:4, req:['customer-interviews','summarising'],
    desc:'Say in one sentence who it is for, what changes, and why you.' },
  { id:'mvp', name:'Minimum Viable Product', tier:4, req:['value-proposition','prototyping'],
    desc:'Ship the smallest honest version that can be bought and learned from.' },
  { id:'validation', name:'Validating Demand', tier:5, req:['mvp','experimentation'],
    desc:'Get money or a signed commitment before building the rest of it.' },
  { id:'business-model', name:'Business Model Design', tier:5, req:['value-proposition','unit-economics'],
    desc:'How value is created, delivered and captured — and why the margins work.' },
]);

addSkills({ cat: 'business', group: 'Selling' }, [
  { id:'sales-basics', name:'Sales Fundamentals', tier:3, req:['asking','listening'],
    desc:'Qualify, understand the need, propose, and ask for the order.' },
  { id:'pitching', name:'Pitching', tier:4, req:['storytelling','presentations'],
    desc:'Ten minutes that makes a stranger want the next meeting.' },
  { id:'objection-handling', name:'Handling Objections', tier:4, req:['sales-basics','perspective-taking'],
    desc:'Treat the objection as information and answer the concern underneath it.' },
  { id:'pricing', name:'Pricing', tier:4, req:['unit-economics','value-proposition'],
    desc:'Price on value and willingness to pay, then test it rather than guessing once.' },
  { id:'proposals', name:'Writing Proposals', tier:4, req:['persuasive-writing','unit-economics'],
    desc:'Scope, deliverables, price and terms that protect both sides.' },
  { id:'contract-negotiation', name:'Negotiating Contracts', tier:5, req:['proposals','negotiation','contracts-reading'],
    desc:'Redline the terms that actually bite: liability, IP, termination and payment.' },
  { id:'account-management', name:'Keeping Customers', tier:4, req:['sales-basics','trust-building'],
    desc:'Retention, renewals and being easy to work with after the sale.' },
  { id:'sales-pipeline', name:'Running a Pipeline', tier:5, req:['sales-basics','data-analysis'],
    desc:'Forecast from stages and conversion rates instead of optimism.' },
]);

addSkills({ cat: 'business', group: 'Marketing' }, [
  { id:'positioning', name:'Positioning', tier:4, req:['competitor-analysis','value-proposition'],
    desc:'Choose the category and comparison you want to be judged inside.' },
  { id:'brand', name:'Brand Building', tier:5, req:['positioning','design'],
    desc:'A consistent promise, voice and look that people recognise and trust.' },
  { id:'copywriting', name:'Copywriting', tier:4, req:['persuasive-writing','positioning'],
    desc:'Headlines and pages that convert without lying or shouting.' },
  { id:'content-marketing', name:'Content Marketing', tier:4, req:['copywriting','consistency'],
    desc:'Publish useful things regularly until you are the source people already trust.' },
  { id:'social-media-marketing', name:'Social Media Marketing', tier:4, req:['copywriting','photo-basics'],
    desc:'Build an audience on a platform without becoming a hostage to its algorithm.' },
  { id:'seo', name:'Search Optimisation', tier:4, req:['content-marketing','web-dev'],
    desc:'Intent, structure and links — being found by people already looking.' },
  { id:'paid-acquisition', name:'Paid Acquisition', tier:5, req:['unit-economics','experimentation'],
    desc:'Buy customers profitably, measure properly, and stop when it stops working.' },
  { id:'email-marketing', name:'Email & Direct Marketing', tier:4, req:['copywriting','privacy-management'],
    desc:'A list you own, permission you actually have, and messages people open.' },
  { id:'pr', name:'Press & Public Relations', tier:5, req:['storytelling','networking'],
    desc:'Get covered by giving journalists a story that serves their readers.' },
  { id:'community-marketing', name:'Building a Customer Community', tier:5, req:['community','content-marketing'],
    desc:'Turn users into a group that helps each other and sells for you.' },
]);

addSkills({ cat: 'business', group: 'Running It' }, [
  { id:'business-registration', name:'Setting Up a Business', tier:3, req:['form-filling','legal-literacy'],
    desc:'Structure, registration, bank account and insurance — the boring first week.' },
  { id:'invoicing', name:'Invoicing & Getting Paid', tier:3, req:['business-registration','record-keeping'],
    desc:'Terms, chasing, late fees, and never being embarrassed about asking.' },
  { id:'bookkeeping', name:'Bookkeeping', tier:4, req:['invoicing','spreadsheets'],
    desc:'Record every transaction so the year-end is an afternoon, not a crisis.' },
  { id:'cash-flow', name:'Cash Flow Management', tier:4, req:['bookkeeping','spreadsheet-modelling'],
    desc:'Profitable businesses die of cash; forecast thirteen weeks out and watch it.' },
  { id:'unit-economics', name:'Unit Economics', tier:4, req:['bookkeeping','estimation'],
    desc:'What one customer costs to get and serve, and what they are worth.' },
  { id:'business-tax', name:'Business Tax & Payroll', tier:5, req:['bookkeeping','self-assessment'],
    desc:'VAT, corporation tax, payroll and deadlines that carry automatic penalties.' },
  { id:'compliance', name:'Regulatory Compliance', tier:4, req:['legal-literacy','record-keeping'],
    desc:'Licences, data protection, health and safety — the rules for your specific trade.' },
  { id:'suppliers', name:'Suppliers & Procurement', tier:4, req:['negotiating-price','contracts-reading'],
    desc:'Choose, negotiate with and second-source the people you depend on.' },
  { id:'operations', name:'Operations & Process', tier:5, req:['project-planning','systems-thinking'],
    desc:'Turn what you do into a repeatable process someone else can run.' },
  { id:'quality-systems', name:'Quality Management', tier:5, req:['operations','assessment'],
    desc:'Standards, checks and a feedback loop that catches defects before customers do.' },
  { id:'customer-service', name:'Customer Service', tier:3, req:['empathy','de-escalation'],
    desc:'Fix the problem, fast, and make the person feel taken seriously while you do.' },
]);

addSkills({ cat: 'business', group: 'Growth & Strategy' }, [
  { id:'entrepreneurship', name:'Entrepreneurship', tier:5, req:['project-planning','negotiation','investing'],
    desc:'Turn a need into an offer, customers and a business that sustains itself.' },
  { id:'fundraising-business', name:'Raising Investment', tier:5, req:['pitching','financial-statements','business-model'],
    desc:'Understand dilution and terms, and pick investors you can live with for a decade.' },
  { id:'business-planning', name:'Business Planning', tier:5, req:['cash-flow','market-sizing','strategic-thinking'],
    desc:'A plan with numbers, assumptions and the conditions under which you would change it.' },
  { id:'scaling', name:'Scaling', tier:5, req:['operations','team-building','cash-flow'],
    desc:'Grow throughput without the quality, the culture or the cash collapsing.' },
  { id:'partnerships', name:'Partnerships & Alliances', tier:5, req:['contract-negotiation','stakeholders'],
    desc:'Find distribution through someone else’s customers without giving away the business.' },
  { id:'internationalisation', name:'Going International', tier:5, req:['localisation','compliance','suppliers'],
    desc:'Enter another market with its own rules, tax, language and expectations.' },
  { id:'turnaround', name:'Turning a Business Around', tier:5, req:['cash-flow','change-management','firing'],
    desc:'Stop the bleeding, cut hard and early, and rebuild around what still works.' },
  { id:'business-exit', name:'Selling or Closing a Business', tier:5, req:['financial-statements','contract-negotiation','business-tax'],
    desc:'Prepare, value, diligence and hand over — or wind up cleanly without leaving debts.' },
  { id:'social-enterprise', name:'Social Enterprise', tier:5, req:['business-model','governance','impact-measurement'],
    desc:'Build something that pays for itself while the mission stays the point.' },
  { id:'impact-measurement', name:'Measuring Impact', tier:4, req:['research-design','data-analysis'],
    desc:'Evidence that you changed something, not just that you did something.' },
]);

addSkills({ cat: 'business', group: 'Small & Solo Business' }, [
  { id:'freelancing', name:'Freelancing', tier:4, req:['invoicing','client-work','personal-marketing'],
    desc:'Find work, price it, deliver it and get paid — repeatedly, without a salary.' },
  { id:'market-stall', name:'Selling in Person', tier:4, req:['sales-basics','pricing'],
    desc:'Markets, fairs and pop-ups: stock, float, display and reading a passing crowd.' },
  { id:'ecommerce', name:'Selling Online', tier:4, req:['photo-basics','copywriting','payment-methods'],
    desc:'Listings, shipping, returns and reviews on a marketplace or your own store.' },
  { id:'dropship-scepticism', name:'Evaluating Business Opportunities', tier:4, req:['unit-economics','fraud-defence'],
    desc:'Run the numbers on any scheme before the person selling it runs them for you.' },
  { id:'side-business', name:'Running a Business on the Side', tier:5, req:['side-income','operations','work-life-boundaries'],
    desc:'A real second business that does not quietly consume every evening you have.' },
  { id:'family-business', name:'Working in a Family Business', tier:5, req:['family-boundaries','governance','succession'],
    desc:'Keep the roles, the money and the dinner table from contaminating each other.' },
  { id:'succession', name:'Succession Planning', tier:5, req:['hiring','handover','wills'],
    desc:'Decide who takes over and prepare them, years before you intend to leave.' },
]);

addSkills({ cat: 'business', group: 'Analysis & Judgement' }, [
  { id:'business-metrics', name:'Choosing Metrics', tier:4, req:['data-analysis','unit-economics'],
    desc:'Pick the few numbers that reflect health, and resist the ones that flatter.' },
  { id:'forecast-modelling', name:'Financial Modelling', tier:5, req:['spreadsheet-modelling','financial-statements'],
    desc:'A model with drivers and scenarios rather than a row of hopeful percentages.' },
  { id:'due-diligence', name:'Due Diligence', tier:5, req:['financial-statements','contracts-reading','investigative-method'],
    desc:'Check what you are told before you commit money or a name to it.' },
  { id:'competitive-strategy', name:'Competitive Strategy', tier:5, req:['strategic-thinking','competitor-analysis'],
    desc:'Build an advantage that survives someone competent trying to copy it.' },
  { id:'business-ethics', name:'Business Ethics', tier:5, req:['professional-ethics','stakeholders'],
    desc:'Decide what you will not do for money, in advance and in writing.' },
]);

addSkills({ cat: 'business', group: 'Commercial Basics' }, [
  { id:'commercial-awareness', name:'Commercial Awareness', tier:2, req:['money-basics'],
    desc:'Know how the place you work actually makes money, and where the margin is.' },
  { id:'customer-facing', name:'Serving Customers', tier:2, req:['politeness','listening'],
    desc:'Greet, help, handle a queue and stay pleasant with the twentieth difficult person.' },
  { id:'handling-cash', name:'Handling Money & Stock', tier:2, req:['numeracy','attention-to-detail'],
    desc:'Float, reconciliation, stock counts and spotting a discrepancy the same day.' },
  { id:'upselling', name:'Suggesting & Upselling', tier:3, req:['customer-facing','sales-basics'],
    desc:'Recommend what genuinely helps, which is also what sells sustainably.' },
  { id:'complaint-handling', name:'Handling a Complaint', tier:3, req:['customer-facing','de-escalation'],
    desc:'Apologise, fix it, and turn an angry customer into a returning one.' },
  { id:'shift-supervision', name:'Supervising a Shift', tier:3, req:['customer-facing','delegation-basics'],
    desc:'Run a floor: cover breaks, allocate jobs and deal with what comes up.' },
  { id:'delegation-basics', name:'Asking Others to Do Things', tier:3, req:['asking','explaining'],
    desc:'Give a clear instruction with a deadline and a reason, then check.' },
  { id:'rota-planning', name:'Planning a Rota', tier:3, req:['shift-supervision','time-management'],
    desc:'Cover, fairness, costs and the people who always want the same Saturday off.' },
  { id:'inventory', name:'Stock & Inventory Control', tier:4, req:['handling-cash','spreadsheets'],
    desc:'Reorder points, shrinkage and not tying up all your cash in the stockroom.' },
  { id:'point-of-sale', name:'Business Systems & Tills', tier:3, req:['handling-cash','workplace-tools'],
    desc:'POS, bookings and card machines set up so the numbers reconcile automatically.' },
]);

addSkills({ cat: 'business', group: 'Sector Craft' }, [
  { id:'hospitality-business', name:'Running a Food Business', tier:5, req:['restaurant-work','operations','food-safety-management'],
    desc:'Covers, margins, staffing and hygiene ratings in a very unforgiving trade.' },
  { id:'retail-business', name:'Running a Shop', tier:5, req:['inventory','point-of-sale','positioning'],
    desc:'Footfall, buying, display and rent — retail arithmetic that is tighter than it looks.' },
  { id:'services-business', name:'Running a Services Business', tier:5, req:['billable-work','rota-planning','account-management'],
    desc:'Utilisation, scheduling and quality when the product is people’s time.' },
  { id:'saas-business', name:'Running a Software Product', tier:5, req:['product-thinking','unit-economics','release-management'],
    desc:'Churn, activation and support load as the numbers that actually decide it.' },
  { id:'agency-business', name:'Running an Agency', tier:5, req:['client-work','hiring','forecast-modelling'],
    desc:'Pipeline, utilisation and the dependency on two big clients.' },
  { id:'nonprofit-management', name:'Running a Charity', tier:5, req:['fundraising','governance','impact-measurement'],
    desc:'Restricted funds, trustees, reporting and mission drift.' },
]);

addSkills({ cat: 'business', group: 'Thinking Commercially' }, [
  { id:'reading-a-market', name:'Reading a Market', tier:4, req:['competitor-analysis','observation'],
    desc:'Notice what is changing in demand, supply and regulation before it is obvious.' },
  { id:'customer-empathy', name:'Understanding Customers', tier:4, req:['customer-interviews','empathy'],
    desc:'Know their day, their constraints and what they are compared against.' },
  { id:'saying-no-business', name:'Turning Down Work', tier:4, req:['saying-no','pricing'],
    desc:'Decline the client, project or market that would cost more than it pays.' },
  { id:'business-focus', name:'Focus', tier:5, req:['strategic-thinking','saying-no-business'],
    desc:'Do one thing properly instead of five things adequately, for long enough to win.' },
  { id:'reputation', name:'Building a Reputation', tier:5, req:['quality-of-work','account-management','integrity'],
    desc:'Deliver consistently for years so most work arrives by recommendation.' },
]);
