/* ==================================================================
   Career & Work — getting hired, being good at a job, and steering a
   working life over forty years.
================================================================== */

addSkills({ cat: 'career', group: 'Getting Hired' }, [
  { id:'cv-writing', name:'Writing a CV', tier:3, req:['sentence-craft','summarising'],
    desc:'One page of evidence, tailored per application, with results rather than duties.' },
  { id:'cover-letter', name:'Cover Letters & Applications', tier:4, req:['cv-writing','persuasive-writing'],
    desc:'Answer why this job, why you, and why now, in three short paragraphs.' },
  { id:'job-search', name:'Job Searching', tier:3, req:['cv-writing','web-search'],
    desc:'Find the roles that are not advertised, and apply to fewer, better.' },
  { id:'interview-skills', name:'Interviewing Well', tier:4, req:['public-speaking','storytelling'],
    desc:'Structured answers with real examples, and questions that show you did the work.' },
  { id:'technical-interview', name:'Technical Interviews', tier:4, req:['interview-skills','algorithms'],
    desc:'Think out loud, clarify the problem, and stay coherent while being watched.' },
  { id:'portfolio', name:'Building a Portfolio', tier:3, req:['cv-writing','design'],
    desc:'Show finished work with the reasoning behind it, not just the pretty output.' },
  { id:'references', name:'References & Recommendations', tier:3, req:['networking','asking'],
    desc:'Cultivate people who will speak for you, and brief them properly.' },
  { id:'salary-negotiation', name:'Negotiating an Offer', tier:4, req:['negotiation','market-research-self'],
    desc:'Know the band, let them go first, and negotiate the whole package.' },
  { id:'market-research-self', name:'Knowing Your Market Value', tier:3, req:['job-search','data-analysis'],
    desc:'Find out what people with your skills are actually paid, from several sources.' },
  { id:'onboarding', name:'Starting a New Job Well', tier:3, req:['workplace-norms','question-asking-social'],
    desc:'Learn the map, meet everyone, and get one visible win in the first month.' },
]);

addSkills({ cat: 'career', group: 'Doing the Work' }, [
  { id:'payslip', name:'Reading a Payslip & Contract', tier:3, req:['money-basics','contracts-reading'],
    desc:'Gross, net, deductions, notice period and what you actually agreed to.' },
  { id:'workplace-norms', name:'Workplace Norms', tier:2, req:['politeness','reading-the-room'],
    desc:'Dress, hours, tone, escalation and the unwritten rules of this particular place.' },
  { id:'email-professional', name:'Professional Writing', tier:3, req:['email-competence','register'],
    desc:'Emails and messages that are short, clear, and impossible to misread.' },
  { id:'meetings', name:'Meetings', tier:3, req:['turn-taking','summarising'],
    desc:'Contribute usefully, take actions, and leave knowing what was decided.' },
  { id:'running-meetings', name:'Running a Meeting', tier:4, req:['meetings','facilitation'],
    desc:'Agenda, timebox, decision, owners — or cancel it and send a note instead.' },
  { id:'task-prioritisation', name:'Prioritisation', tier:3, req:['time-management','decision-making'],
    desc:'Work out what actually matters this week and let the rest visibly wait.' },
  { id:'project-planning', name:'Project Planning', tier:4, req:['time-management'],
    desc:'Scope, sequence and track work with dependencies and a real deadline.' },
  { id:'estimating-work', name:'Estimating Work', tier:4, req:['project-planning','estimation'],
    desc:'Give a range, state assumptions, and get better by comparing to what happened.' },
  { id:'status-reporting', name:'Reporting Progress', tier:3, req:['summarising','email-professional'],
    desc:'Say where things stand, including bad news, early and without drama.' },
  { id:'documentation', name:'Documenting Your Work', tier:4, req:['technical-writing','file-org'],
    desc:'Write it down so the next person, including future you, does not have to ask.' },
  { id:'handover', name:'Handing Over', tier:4, req:['documentation','mentoring'],
    desc:'Leave a role so cleanly that your successor is glad rather than resentful.' },
]);

addSkills({ cat: 'career', group: 'Working With People' }, [
  { id:'collaboration', name:'Collaboration', tier:3, req:['meetings','feedback'],
    desc:'Do your part, share early, and make the shared thing better than your bit.' },
  { id:'managing-up', name:'Managing Upwards', tier:4, req:['status-reporting','email-professional'],
    desc:'Give your manager what they need to help you, before they have to ask.' },
  { id:'stakeholders', name:'Stakeholder Management', tier:4, req:['managing-up','group-dynamics'],
    desc:'Map who cares, what they need, and keep each of them appropriately informed.' },
  { id:'office-politics', name:'Organisational Politics', tier:4, req:['group-dynamics','stakeholders'],
    desc:'Read power and incentive honestly, and operate in it without becoming unpleasant.' },
  { id:'difficult-colleagues', name:'Difficult Colleagues', tier:4, req:['conflict','boundaries'],
    desc:'Work productively with someone you would not choose, and escalate only when needed.' },
  { id:'workplace-grievance', name:'Raising a Serious Problem', tier:5, req:['employment-rights','courage','record-keeping'],
    desc:'Document, report and pursue harassment or misconduct through the proper channel.' },
  { id:'cross-functional', name:'Working Across Functions', tier:4, req:['stakeholders','explaining'],
    desc:'Speak engineering to sales and finance to design without losing the substance.' },
]);

addSkills({ cat: 'career', group: 'Managing' }, [
  { id:'delegation', name:'Delegation', tier:4, req:['project-planning','trust-building'],
    desc:'Hand over outcome and authority, not just tasks, and resist taking it back.' },
  { id:'one-to-ones', name:'Running One-to-Ones', tier:4, req:['mentoring','listening'],
    desc:'A regular half-hour that is theirs, where the real problems actually surface.' },
  { id:'performance-management', name:'Performance Management', tier:5, req:['one-to-ones','feedback','assessment'],
    desc:'Set expectations, evidence them, and address underperformance early and fairly.' },
  { id:'hiring', name:'Hiring', tier:5, req:['interviewing','bias-awareness','job-description'],
    desc:'Define the role, run a fair structured process, and make the call.' },
  { id:'job-description', name:'Defining a Role', tier:4, req:['project-planning','technical-writing'],
    desc:'Write what the job is for and what good looks like, before anyone applies.' },
  { id:'firing', name:'Letting Someone Go', tier:5, req:['performance-management','difficult-conversations','employment-rights'],
    desc:'Do it lawfully, once, with dignity, and having tried everything reasonable first.' },
  { id:'team-building', name:'Building a Team', tier:5, req:['hiring','delegation','group-dynamics'],
    desc:'Assemble complementary people and give them a way of working they own.' },
  { id:'remote-management', name:'Managing Remotely', tier:5, req:['delegation','remote-collaboration','one-to-ones'],
    desc:'Manage outcomes and trust across timezones without surveillance.' },
  { id:'change-management', name:'Leading Change', tier:5, req:['team-building','persuasion','systems-thinking'],
    desc:'Move an organisation to a new way of working and make it stick past month three.' },
]);

addSkills({ cat: 'career', group: 'Steering a Career' }, [
  { id:'career-planning', name:'Career Planning', tier:3, req:['strengths-audit','decision-making'],
    desc:'Decide what you want to be good at, and choose next roles that build toward it.' },
  { id:'skill-gap-analysis', name:'Closing a Skill Gap', tier:4, req:['career-planning','self-directed'],
    desc:'Identify precisely what is between you and the next role, and go get it.' },
  { id:'personal-marketing', name:'Being Known for Something', tier:4, req:['portfolio','networking'],
    desc:'Become the obvious person for a specific problem in your field.' },
  { id:'promotion', name:'Getting Promoted', tier:4, req:['managing-up','personal-marketing','status-reporting'],
    desc:'Do the next job before you have it and make the evidence easy to find.' },
  { id:'career-change', name:'Changing Career', tier:5, req:['skill-gap-analysis','emergency-fund','rapid-skill'],
    desc:'Cross into a new field on transferable evidence, with the runway to survive it.' },
  { id:'sabbatical', name:'Taking a Career Break', tier:4, req:['emergency-fund','career-planning'],
    desc:'Plan, fund and return from time out without it derailing everything.' },
  { id:'redundancy', name:'Handling Redundancy', tier:4, req:['employment-rights','emergency-fund','resilience'],
    desc:'Understand the process and your entitlement, and start the next search fast.' },
  { id:'portfolio-career', name:'A Portfolio Career', tier:5, req:['freelance-finance','personal-marketing','task-prioritisation'],
    desc:'Combine several income streams deliberately rather than by accident.' },
  { id:'work-life-boundaries', name:'Work–Life Boundaries', tier:4, req:['boundaries','saying-no','recovery-cycles'],
    desc:'Protect hours, attention and identity that belong to the rest of your life.' },
  { id:'retirement-transition', name:'Retiring Well', tier:5, req:['retirement-planning','purpose','community-participation'],
    desc:'Replace what a job was providing beyond money before you stop doing it.' },
]);

addSkills({ cat: 'career', group: 'Trades & Professional Practice' }, [
  { id:'apprenticeship-route', name:'Learning a Trade', tier:4, req:['apprenticeship','tool-handling'],
    desc:'Time served under someone competent, plus the tickets the work legally requires.' },
  { id:'professional-registration', name:'Professional Registration', tier:4, req:['credential-strategy','bureaucracy'],
    desc:'Chartership, licensure and CPD — the gates on regulated professions.' },
  { id:'professional-ethics', name:'Professional Ethics', tier:4, req:['integrity','compliance'],
    desc:'Duty of care, conflicts of interest and the code you can actually be struck off for.' },
  { id:'client-work', name:'Working With Clients', tier:4, req:['stakeholders','proposals'],
    desc:'Scope, expectations, revisions and the conversation before the work goes wrong.' },
  { id:'billable-work', name:'Selling Your Time', tier:4, req:['pricing','time-management'],
    desc:'Rates, utilisation and understanding what an hour of you actually costs.' },
  { id:'consulting', name:'Consulting', tier:5, req:['client-work','problem-spotting','presentations'],
    desc:'Diagnose, recommend and be useful in an organisation you joined last week.' },
  { id:'expert-witness', name:'Giving Expert Evidence', tier:5, req:['professional-registration','impromptu','legal-literacy'],
    desc:'Explain your field to a court and survive cross-examination of your reasoning.' },
]);

addSkills({ cat: 'career', group: 'Workplace Wellbeing' }, [
  { id:'imposter-syndrome', name:'Handling Imposter Feelings', tier:4, req:['self-concept','handling-criticism'],
    desc:'Function well while feeling underqualified, and check the feeling against evidence.' },
  { id:'workload-negotiation', name:'Negotiating Workload', tier:4, req:['saying-no','managing-up','estimating-work'],
    desc:'Push back with options and trade-offs instead of absorbing everything silently.' },
  { id:'burnout-recovery', name:'Recovering From Burnout', tier:5, req:['stress-management','work-life-boundaries','help-seeking'],
    desc:'Recognise it, stop, and change the conditions rather than just resting once.' },
  { id:'toxic-workplace', name:'Leaving a Bad Job', tier:4, req:['redundancy','job-search','boundaries'],
    desc:'Recognise a workplace that will not improve and exit on your own terms.' },
  { id:'meaningful-work', name:'Finding Meaning in Work', tier:5, req:['purpose','career-planning'],
    desc:'Connect what you do daily to something you actually care about, or change one.' },
]);

addSkills({ cat: 'career', group: 'Starting Out' }, [
  { id:'work-ethic', name:'Turning Up and Working', tier:1,
    desc:'On time, ready, doing the boring parts — the baseline everything else sits on.' },
  { id:'taking-instruction', name:'Taking Instruction', tier:1,
    desc:'Listen, confirm what was asked, and check back before going a long way wrong.' },
  { id:'first-job', name:'Your First Job', tier:2, req:['work-ethic','taking-instruction'],
    desc:'Shifts, uniform, tills and customers — the ordinary competence of paid work.' },
  { id:'work-experience', name:'Work Experience & Internships', tier:2, req:['first-job','question-asking-social'],
    desc:'Be useful, be curious, and leave with a contact who remembers you.' },
  { id:'asking-for-work', name:'Asking for Work', tier:3, req:['asking','first-job'],
    desc:'Walk in, write, or ask someone — most first jobs come from asking directly.' },
  { id:'timekeeping-work', name:'Reliability at Work', tier:2, req:['punctuality','promise-keeping'],
    desc:'Rota, notice, sickness and shift swaps handled like an adult.' },
  { id:'workplace-tools', name:'Learning Workplace Systems', tier:2, req:['computer-literacy','troubleshooting'],
    desc:'Get productive fast in whatever software this particular employer uses.' },
]);

addSkills({ cat: 'career', group: 'Craft of the Job' }, [
  { id:'attention-to-detail', name:'Attention to Detail', tier:2, req:['checklists','single-tasking'],
    desc:'Catch your own errors before someone else has to, as a matter of routine.' },
  { id:'initiative', name:'Taking Initiative', tier:3, req:['work-ethic','problem-spotting'],
    desc:'See the thing that needs doing and do it without being told to.' },
  { id:'quality-of-work', name:'Doing Good Work', tier:3, req:['attention-to-detail','feedback'],
    desc:'Hold a standard when nobody would notice if you dropped it.' },
  { id:'working-fast', name:'Working Quickly', tier:4, req:['quality-of-work','task-prioritisation'],
    desc:'Find the speed that does not cost accuracy, and know where the ceiling is.' },
  { id:'note-to-self', name:'Working Notes', tier:2, req:['notetaking','file-org'],
    desc:'Keep a running log so you can reconstruct what you did and why, months later.' },
  { id:'saying-i-dont-know', name:'Admitting Ignorance', tier:3, req:['self-honesty','asking'],
    desc:'Say you do not know, then go and find out — faster than pretending.' },
  { id:'escalation', name:'Knowing When to Escalate', tier:3, req:['risk-assessment','status-reporting'],
    desc:'Raise it early enough that it is still someone’s problem rather than a crisis.' },
]);

addSkills({ cat: 'career', group: 'Communication at Work' }, [
  { id:'writing-for-decision', name:'Writing for a Decision', tier:4, req:['summarising','email-professional'],
    desc:'Recommendation first, options and trade-offs after, one page maximum.' },
  { id:'presenting-at-work', name:'Presenting at Work', tier:4, req:['presentations','public-speaking'],
    desc:'Know who is in the room, what they must decide, and finish early.' },
  { id:'giving-bad-news', name:'Delivering Bad News', tier:4, req:['status-reporting','difficult-conversations'],
    desc:'Say it plainly, early, with what you are doing about it.' },
  { id:'meeting-notes', name:'Minutes & Follow-Up', tier:3, req:['meetings','note-to-self'],
    desc:'Decisions, owners and dates circulated within an hour of the meeting.' },
  { id:'internal-comms', name:'Communicating Across an Organisation', tier:5, req:['writing-for-decision','change-management'],
    desc:'Say the same true thing repeatedly until it has actually landed everywhere.' },
  { id:'crisis-comms', name:'Communicating in a Crisis', tier:5, req:['giving-bad-news','pr','oncall'],
    desc:'Fast, honest, frequent updates that hold trust while you still lack facts.' },
]);
