/* ==================================================================
   Visual Arts & Design — seeing, drawing, photographing, filming and
   designing things other people have to look at.
================================================================== */

addSkills({ cat: 'creative', group: 'Seeing' }, [
  { id:'visual-literacy', name:'Visual Literacy', tier:1,
    desc:'Read an image for what it emphasises, omits and is trying to make you feel.' },
  { id:'colour-theory', name:'Colour Theory', tier:2, req:['visual-literacy'],
    desc:'Hue, value, saturation and the relationships that make a palette work.' },
  { id:'composition', name:'Composition & Framing', tier:2, req:['photo-basics','sketching'],
    desc:'Arrange a frame so the eye goes where you want it to go.' },
  { id:'observation-drawing', name:'Drawing What You Actually See', tier:2, req:['sketching'],
    desc:'Override what you think a hand looks like and draw the shape in front of you.' },
  { id:'art-critique', name:'Critiquing Work', tier:3, req:['visual-literacy','feedback'],
    desc:'Say what a piece is doing and whether it works, without saying whether you like it.' },
]);

addSkills({ cat: 'creative', group: 'Drawing & Painting' }, [
  { id:'sketching', name:'Sketching', tier:1,
    desc:'Get what you see, or imagine, onto paper quickly and loosely.' },
  { id:'drawing', name:'Drawing Fundamentals', tier:2, req:['sketching'],
    desc:'Perspective, proportion, value and shading from observation.' },
  { id:'figure-drawing', name:'Figure Drawing', tier:3, req:['drawing','observation-drawing'],
    desc:'Gesture, anatomy and foreshortening — the hardest and most useful subject.' },
  { id:'perspective', name:'Perspective & Architecture', tier:3, req:['drawing','geometry'],
    desc:'One-, two- and three-point perspective that holds up in a complex scene.' },
  { id:'inking', name:'Ink & Line Work', tier:3, req:['drawing','fine-motor'],
    desc:'Confident line weight, hatching and marks you cannot undo.' },
  { id:'painting', name:'Colour & Painting', tier:3, req:['drawing','composition'],
    desc:'Colour theory, mixing and medium control in paint.' },
  { id:'watercolour', name:'Watercolour', tier:4, req:['painting'],
    desc:'Water control, layering and letting the medium do half the work.' },
  { id:'oil-acrylic', name:'Oil & Acrylic Painting', tier:4, req:['painting','colour-theory'],
    desc:'Underpainting, glazing and impasto — building an image in layers over days.' },
  { id:'life-painting', name:'Portrait & Life Painting', tier:5, req:['oil-acrylic','figure-drawing'],
    desc:'Capture a likeness and a presence from a live sitter in limited time.' },
  { id:'printmaking', name:'Printmaking', tier:4, req:['inking','fine-motor'],
    desc:'Lino, etching or screen — thinking in reverse, in layers, in editions.' },
  { id:'sculpture', name:'Sculpture', tier:4, req:['observation-drawing','proprioception'],
    desc:'Form in three dimensions: mass, armature, and it reading from every angle.' },
]);

addSkills({ cat: 'creative', group: 'Photography' }, [
  { id:'photo-basics', name:'Photography Basics', tier:1,
    desc:'Exposure, focus and light — taking a photo on purpose rather than by luck.' },
  { id:'exposure-triangle', name:'Manual Exposure', tier:2, req:['photo-basics'],
    desc:'Aperture, shutter and ISO traded against each other with intent.' },
  { id:'light-reading', name:'Reading Light', tier:3, req:['exposure-triangle','visual-literacy'],
    desc:'Direction, quality and colour of light, and waiting for the right hour.' },
  { id:'portrait-photo', name:'Portrait Photography', tier:4, req:['light-reading','empathy'],
    desc:'Direct a nervous person and light them so they look like themselves.' },
  { id:'documentary-photo', name:'Documentary & Street', tier:4, req:['light-reading','composition'],
    desc:'Anticipate a moment, be close, and be ethical about photographing strangers.' },
  { id:'landscape-photo', name:'Landscape Photography', tier:4, req:['light-reading','weather-reading'],
    desc:'Planning, conditions, filters and being there at five in the morning.' },
  { id:'studio-lighting', name:'Studio Lighting', tier:4, req:['light-reading','electricity-basics'],
    desc:'Key, fill and rim with strobes and modifiers, built up one light at a time.' },
  { id:'photo-editing', name:'Photo Editing', tier:3, req:['photo-basics','colour-theory'],
    desc:'Raw processing, tone curves and retouching that serves the picture.' },
  { id:'photo-project', name:'A Photographic Body of Work', tier:5, req:['documentary-photo','photo-editing','editing'],
    desc:'Shoot, sequence and edit thirty images that say one thing together.' },
]);

addSkills({ cat: 'creative', group: 'Moving Image' }, [
  { id:'video-basics', name:'Shooting Video', tier:2, req:['photo-basics'],
    desc:'Frame rates, stability, audio and coverage that will actually cut together.' },
  { id:'video-editing', name:'Video Editing', tier:3, req:['composition'],
    desc:'Cut footage into pace and meaning; sound, colour and rhythm of a timeline.' },
  { id:'cinematography', name:'Cinematography', tier:4, req:['light-reading','video-basics'],
    desc:'Lens, movement and lighting choices that carry the story rather than decorate it.' },
  { id:'sound-recording', name:'Location Sound', tier:3, req:['video-basics','hearing-care'],
    desc:'Mics, levels and room — the half of film that audiences notice when it is bad.' },
  { id:'screenwriting', name:'Screenwriting', tier:4, req:['fiction','storytelling'],
    desc:'Structure, scene and dialogue in a format a crew can shoot.' },
  { id:'directing', name:'Directing', tier:5, req:['cinematography','screenwriting','leadership'],
    desc:'Hold the vision, work with actors, and make a hundred decisions a day.' },
  { id:'filmmaking', name:'Filmmaking', tier:4, req:['video-editing','storytelling'],
    desc:'Take a film from script through shoot to finished cut.' },
  { id:'motion-graphics', name:'Motion Graphics', tier:4, req:['video-editing','design'],
    desc:'Type, shape and timing animated with restraint and good easing.' },
  { id:'animation', name:'Animation', tier:5, req:['drawing','motion-graphics'],
    desc:'Timing, weight and anticipation — making drawings appear to be alive.' },
  { id:'documentary-making', name:'Documentary Filmmaking', tier:5, req:['filmmaking','interviewing','research-ethics'],
    desc:'Find the story in real life without bending the people in it out of shape.' },
]);

addSkills({ cat: 'creative', group: 'Design' }, [
  { id:'design', name:'Design Principles', tier:3, req:['composition','drawing'],
    desc:'Hierarchy, type, spacing and colour applied to something someone must use.' },
  { id:'typography', name:'Typography', tier:3, req:['design'],
    desc:'Typeface, size, measure and leading — the invisible craft of readable text.' },
  { id:'layout', name:'Layout & Grids', tier:4, req:['typography','composition'],
    desc:'Systems that hold a magazine, a report or a site together across pages.' },
  { id:'ux-design', name:'UX Design', tier:4, req:['design','customer-interviews'],
    desc:'Flows, states and edge cases designed for what people actually do.' },
  { id:'ui-design', name:'UI Design', tier:4, req:['ux-design','typography'],
    desc:'Components, spacing and affordances that feel obvious and stay consistent.' },
  { id:'design-systems', name:'Design Systems', tier:5, req:['ui-design','documentation'],
    desc:'Tokens, components and rules so a whole team can produce consistent work.' },
  { id:'branding-design', name:'Identity Design', tier:5, req:['typography','brand'],
    desc:'Marks, palettes and guidelines that stay recognisable at every size.' },
  { id:'information-design', name:'Information Design', tier:5, req:['data-viz','layout'],
    desc:'Make a complicated thing understandable at a glance — maps, diagrams, dashboards.' },
  { id:'accessibility-design', name:'Accessible Design', tier:4, req:['ui-design','inclusion'],
    desc:'Contrast, focus order, alt text and targets that make it usable by everyone.' },
  { id:'game-design', name:'Game Design', tier:4, req:['systems-thinking','ux-design'],
    desc:'Rules, feedback and difficulty curves that make play compelling.' },
  { id:'exhibition-design', name:'Exhibition & Spatial Design', tier:5, req:['layout','sculpture'],
    desc:'Design a route through a room so meaning unfolds in the right order.' },
]);

addSkills({ cat: 'creative', group: 'Writing' }, [
  { id:'journaling', name:'Journaling', tier:1,
    desc:'Write regularly for yourself; the habit that feeds every other writing skill.' },
  { id:'creative-writing', name:'Creative Writing', tier:2, req:['journaling'],
    desc:'Voice, imagery and scene — writing that is meant to be read.' },
  { id:'fiction', name:'Fiction & Poetry', tier:3, req:['creative-writing'],
    desc:'Sustain plot, character and form across a finished short work.' },
  { id:'dialogue', name:'Writing Dialogue', tier:3, req:['creative-writing','listening'],
    desc:'Speech that sounds like a person and carries the scene at the same time.' },
  { id:'worldbuilding', name:'Worldbuilding', tier:4, req:['fiction','systems-thinking'],
    desc:'Invent a coherent place with its own history, economy and constraints.' },
  { id:'long-form', name:'Long-Form Writing', tier:4, req:['fiction','essay-writing'],
    desc:'Carry structure, argument and voice across book- or novella-length work.' },
  { id:'poetry', name:'Poetry', tier:4, req:['creative-writing','sentence-craft'],
    desc:'Compression, line, sound and form — every word load-bearing.' },
  { id:'writing-practice', name:'A Writing Practice', tier:4, req:['creative-writing','consistency'],
    desc:'Words on the page most days for years, independent of inspiration.' },
]);

addSkills({ cat: 'creative', group: 'Making a Life of It' }, [
  { id:'digital-art', name:'Digital Illustration', tier:4, req:['painting','design'],
    desc:'Produce finished illustration work in a digital pipeline.' },
  { id:'creative-process', name:'A Creative Process', tier:4, req:['writing-practice','art-critique'],
    desc:'Reliable routes from blank page to finished thing that do not need a muse.' },
  { id:'artistic-voice', name:'Artistic Voice', tier:5, req:['digital-art','long-form'],
    desc:'Work that is recognisably yours — consistent taste, obsessions and choices.' },
  { id:'commissions', name:'Working to a Brief', tier:4, req:['design','proposals'],
    desc:'Deliver someone else’s vision on time, and manage revision rounds in the contract.' },
  { id:'publishing', name:'Publishing & Exhibiting', tier:5, req:['long-form','networking'],
    desc:'Get finished work in front of a real audience through real channels.' },
  { id:'creative-direction', name:'Creative Direction', tier:5, req:['design','filmmaking','facilitation'],
    desc:'Set and defend the vision for work that other creatives execute.' },
  { id:'creative-business', name:'Making a Living From Art', tier:5, req:['commissions','pricing','personal-marketing'],
    desc:'Price, licence and diversify so the work pays for the time it takes.' },
]);

addSkills({ cat: 'creative', group: 'Digital Craft' }, [
  { id:'image-editing', name:'Image Editing', tier:3, req:['photo-editing','computer-literacy'],
    desc:'Layers, masks and selections used non-destructively rather than by trial and error.' },
  { id:'vector-graphics', name:'Vector Illustration', tier:3, req:['drawing','computer-literacy'],
    desc:'Bézier curves, boolean shapes and artwork that scales to any size.' },
  { id:'threed-modelling', name:'3D Modelling', tier:4, req:['cad','perspective'],
    desc:'Topology, materials and lighting for an object that renders convincingly.' },
  { id:'digital-painting', name:'Digital Painting', tier:4, req:['painting','image-editing'],
    desc:'Brushes, layers and colour management on a tablet, with traditional fundamentals.' },
  { id:'photo-compositing', name:'Compositing', tier:5, req:['image-editing','light-reading'],
    desc:'Combine sources with matched light, perspective and grain so the seam disappears.' },
  { id:'colour-grading', name:'Colour Grading', tier:5, req:['video-editing','colour-theory'],
    desc:'Match shots, set a look, and stay inside legal broadcast range.' },
  { id:'generative-art', name:'Generative & AI-Assisted Art', tier:5, req:['digital-art','prompting','ai-ethics'],
    desc:'Direct a model as a medium, with a clear view on authorship and sources.' },
]);

addSkills({ cat: 'creative', group: 'Craft of Story' }, [
  { id:'story-structure', name:'Story Structure', tier:3, req:['fiction','summarising'],
    desc:'Setup, turn and consequence — why a scene earns its place in the sequence.' },
  { id:'character', name:'Character Building', tier:4, req:['story-structure','empathy'],
    desc:'Want, need and contradiction, revealed through choices under pressure.' },
  { id:'point-of-view', name:'Point of View & Voice', tier:4, req:['story-structure','prose-style'],
    desc:'Choose who tells it and how much they know, then be ruthlessly consistent.' },
  { id:'revision-fiction', name:'Rewriting Fiction', tier:5, req:['character','editing'],
    desc:'Cut the first three chapters, restructure, and be glad about it.' },
  { id:'workshopping', name:'Writing Groups & Critique', tier:4, req:['art-critique','handling-criticism'],
    desc:'Give useful notes and take them without defending the draft in the room.' },
  { id:'submitting-work', name:'Submitting & Being Rejected', tier:4, req:['workshopping','rejection'],
    desc:'Research markets, submit widely, log it, and keep going for years.' },
]);

addSkills({ cat: 'creative', group: 'Seeing More' }, [
  { id:'museum-looking', name:'Looking at Art', tier:2, req:['visual-literacy'],
    desc:'Spend ten minutes with one work instead of ninety seconds with fifty.' },
  { id:'architecture-literacy', name:'Reading Buildings', tier:3, req:['visual-literacy','historical-context'],
    desc:'Style, structure and use — why a street looks the way it does.' },
  { id:'film-literacy', name:'Reading Film', tier:3, req:['visual-literacy','story-structure'],
    desc:'Shot, cut and sound analysed as choices rather than absorbed as content.' },
  { id:'design-critique', name:'Critiquing Design', tier:4, req:['design','art-critique'],
    desc:'Judge work against its brief and its users, not against your taste.' },
  { id:'curation', name:'Curating', tier:5, req:['museum-looking','art-history','exhibition-design'],
    desc:'Select and sequence work so the collection argues something.' },
]);

addSkills({ cat: 'creative', group: 'Starting to Make' }, [
  { id:'doodling', name:'Doodling', tier:1,
    desc:'Make marks without judging them; the lowest-stakes entry to every visual skill.' },
  { id:'colouring-shading', name:'Colour & Shading Basics', tier:1,
    desc:'Pencil, pen and paint used well enough to enjoy filling a page.' },
  { id:'copying-work', name:'Learning by Copying', tier:2, req:['sketching','observation-drawing'],
    desc:'Reproduce work you admire closely, which teaches more than originality does early.' },
  { id:'sketchbook', name:'Keeping a Sketchbook', tier:2, req:['doodling','journaling'],
    desc:'Fill pages badly and often; the volume is what produces the ability.' },
  { id:'daily-creative', name:'A Daily Creative Habit', tier:3, req:['sketchbook','habits'],
    desc:'Make something small every day and let the average rise on its own.' },
  { id:'sharing-work', name:'Showing People Your Work', tier:3, req:['daily-creative','handling-criticism'],
    desc:'Put it in front of someone before it is ready, and survive that.' },
  { id:'collage', name:'Collage & Mixed Media', tier:2, req:['composition','papercraft'],
    desc:'Compose from found material where the source images do half the work.' },
  { id:'zine-art', name:'Small Format Art', tier:4, req:['collage','printmaking'],
    desc:'Postcards, stickers and prints — finished work at a scale you can actually finish.' },
]);

addSkills({ cat: 'creative', group: 'Working in the Industry' }, [
  { id:'design-brief', name:'Writing a Brief', tier:4, req:['requirements','design'],
    desc:'Define the problem, audience and constraints so the work can be judged.' },
  { id:'art-direction', name:'Art Direction', tier:5, req:['design-critique','branding-design'],
    desc:'Set a visual direction and get photographers and illustrators to hit it.' },
  { id:'production-management', name:'Production Management', tier:5, req:['project-planning','commissions'],
    desc:'Budgets, schedules, crew and permissions for work with a shoot date.' },
  { id:'licensing-art', name:'Licensing Your Work', tier:5, req:['ip-law','creative-business'],
    desc:'Sell usage rather than ownership, and understand what you are giving away.' },
  { id:'artist-statement', name:'Talking About Your Work', tier:4, req:['sharing-work','summarising'],
    desc:'Explain what you make and why without either mystification or apology.' },
]);
