/* ==================================================================
   Food & Cooking — feeding yourself and other people, well, for a
   whole life.
================================================================== */

addSkills({ cat: 'food', group: 'Kitchen Basics' }, [
  { id:'cooking-basics', name:'Basic Cooking', tier:1,
    desc:'Knife safety, heat control, and five meals you can make without a recipe.' },
  { id:'knife-skills', name:'Knife Skills', tier:2, req:['cooking-basics','fine-motor'],
    desc:'Grip, claw and a consistent dice — speed comes from not thinking about it.' },
  { id:'kitchen-hygiene', name:'Food Hygiene', tier:1,
    desc:'Temperatures, cross-contamination, dates and cooling — how not to poison anyone.' },
  { id:'recipe-reading', name:'Following a Recipe', tier:1,
    desc:'Read it all first, mise en place, and notice when the timings are lying.' },
  { id:'seasoning', name:'Seasoning & Tasting', tier:2, req:['cooking-basics'],
    desc:'Salt, acid, fat and heat adjusted by tasting as you go rather than at the end.' },
  { id:'heat-control', name:'Heat & Pan Control', tier:2, req:['cooking-basics'],
    desc:'Know what your hob actually does, and why the pan needs to be hotter than that.' },
  { id:'kitchen-kit', name:'Equipping a Kitchen', tier:2, req:['cooking-basics','comparison-shopping'],
    desc:'The dozen tools worth owning, and the thirty that will sit in a drawer.' },
  { id:'pan-care', name:'Caring for Knives & Pans', tier:3, req:['kitchen-kit','sharpening'],
    desc:'Season cast iron, hone a blade, and stop destroying non-stick.' },
  { id:'leftovers', name:'Using Up Leftovers', tier:2, req:['cooking-basics','kitchen-hygiene'],
    desc:'Turn Sunday into Tuesday and cut a third off the food you throw away.' },
]);

addSkills({ cat: 'food', group: 'Technique' }, [
  { id:'roasting', name:'Roasting & Baking Off', tier:2, req:['heat-control'],
    desc:'Oven temperatures, resting and knowing your oven runs hot on the left.' },
  { id:'frying', name:'Frying & Searing', tier:3, req:['heat-control','seasoning'],
    desc:'Maillard, oil temperature, and not crowding the pan.' },
  { id:'braising', name:'Braising & Slow Cooking', tier:3, req:['roasting','seasoning'],
    desc:'Cheap cuts, time and liquid turned into the best food most people can make.' },
  { id:'stocks-sauces', name:'Stocks & Sauces', tier:4, req:['braising','seasoning'],
    desc:'Stock, reduction, emulsion and pan sauce — where restaurant flavour comes from.' },
  { id:'eggs', name:'Cooking Eggs', tier:2, req:['heat-control'],
    desc:'Omelette, poach, custard — the diagnostic test of heat control.' },
  { id:'vegetables', name:'Cooking Vegetables', tier:2, req:['knife-skills','seasoning'],
    desc:'Season, char and dress vegetables so they are the reason for the meal.' },
  { id:'meat-cookery', name:'Meat & Fish Cookery', tier:4, req:['frying','roasting'],
    desc:'Cuts, doneness, resting and butchery enough to break down a chicken.' },
  { id:'grilling', name:'Grilling & Barbecue', tier:4, req:['frying','fire-craft'],
    desc:'Direct and indirect heat, smoke, and cooking to temperature rather than time.' },
  { id:'plant-based', name:'Cooking Without Animals', tier:3, req:['vegetables','seasoning'],
    desc:'Build umami, protein and satisfaction without defaulting to imitation.' },
  { id:'cooking-advanced', name:'Cooking Repertoire', tier:3, req:['nutrition'],
    desc:'Cook across cuisines and improvise from what is in the fridge.' },
  { id:'improvised-cooking', name:'Cooking Without a Recipe', tier:5, req:['stocks-sauces','cooking-advanced','flavour-pairing'],
    desc:'Open the fridge and produce something good, on purpose, repeatably.' },
  { id:'flavour-pairing', name:'Flavour Building', tier:4, req:['seasoning','cooking-advanced'],
    desc:'Know which aromatics, acids and spices belong together and why.' },
]);

addSkills({ cat: 'food', group: 'Baking' }, [
  { id:'baking-basics', name:'Baking Basics', tier:2, req:['recipe-reading','measurement'],
    desc:'Weigh, don’t scoop; the discipline baking demands that cooking does not.' },
  { id:'cakes', name:'Cakes & Sponges', tier:3, req:['baking-basics','eggs'],
    desc:'Creaming, folding and knowing when it is done without opening the oven.' },
  { id:'bread', name:'Bread Making', tier:3, req:['baking-basics','patience-craft'],
    desc:'Hydration, gluten development, proving and reading the dough not the clock.' },
  { id:'sourdough', name:'Sourdough', tier:4, req:['bread','fermenting'],
    desc:'Keep a starter alive and bake a decent loaf from it, repeatedly.' },
  { id:'pastry', name:'Pastry', tier:4, req:['baking-basics','patience-craft'],
    desc:'Shortcrust, puff and choux — cold hands, rested dough, no shrinkage.' },
  { id:'enriched-dough', name:'Enriched & Laminated Dough', tier:5, req:['pastry','bread'],
    desc:'Brioche and croissants: butter, lamination and a temperature you must respect.' },
  { id:'desserts', name:'Desserts & Confectionery', tier:4, req:['cakes','stocks-sauces'],
    desc:'Custards, meringues, sugar work and plating something that holds together.' },
  { id:'decorating', name:'Cake Decorating', tier:4, req:['cakes','fine-motor','design'],
    desc:'Crumb coat, smooth finish and piping that looks deliberate.' },
]);

addSkills({ cat: 'food', group: 'Preserving & Fermenting' }, [
  { id:'food-storage', name:'Storing Food Properly', tier:1,
    desc:'Fridge zones, freezing, wrapping and dates — most waste is a storage failure.' },
  { id:'freezing', name:'Freezing & Batch Cooking', tier:2, req:['food-storage','leftovers'],
    desc:'Cook once, eat six times, with labels and portions that survive the freezer.' },
  { id:'pickling', name:'Pickling', tier:3, req:['food-storage','kitchen-hygiene'],
    desc:'Vinegar and salt brines that keep vegetables for months, safely.' },
  { id:'fermenting', name:'Fermentation', tier:4, req:['pickling','microbiology'],
    desc:'Kraut, kimchi, kefir and yoghurt — managing microbes deliberately.' },
  { id:'canning', name:'Canning & Bottling', tier:4, req:['pickling','kitchen-hygiene'],
    desc:'Acidity, headspace and processing times that make shelf-stable food safe.' },
  { id:'curing', name:'Curing & Smoking', tier:5, req:['canning','meat-cookery','microbiology'],
    desc:'Salt, nitrate, humidity and time — preservation with a real margin for error.' },
  { id:'drying', name:'Drying & Dehydrating', tier:3, req:['food-storage'],
    desc:'Herbs, fruit and mushrooms dried to a moisture level that will not spoil.' },
]);

addSkills({ cat: 'food', group: 'Cuisines' }, [
  { id:'one-cuisine', name:'One Cuisine Properly', tier:4, req:['cooking-advanced','flavour-pairing'],
    desc:'Learn the pantry, techniques and logic of a single tradition end to end.' },
  { id:'rice-grains', name:'Rice, Grains & Pulses', tier:2, req:['heat-control'],
    desc:'Cook every staple grain and legume to the texture it is supposed to have.' },
  { id:'noodles-pasta', name:'Pasta & Noodles', tier:3, req:['baking-basics','heat-control'],
    desc:'Make it fresh, cook it right, and sauce it in the pan rather than on the plate.' },
  { id:'spice-craft', name:'Spices', tier:3, req:['seasoning','tasting'],
    desc:'Whole vs. ground, blooming, tempering, and building a masala from scratch.' },
  { id:'wok-cooking', name:'Wok Cooking', tier:4, req:['frying','knife-skills'],
    desc:'Heat, prep and speed — stir-frying so nothing steams or overcooks.' },
  { id:'street-food', name:'Street Food Techniques', tier:4, req:['wok-cooking','grilling'],
    desc:'High-heat, fast-assembly dishes built for volume and eaten standing up.' },
  { id:'regional-depth', name:'Cooking Across Cultures', tier:5, req:['one-cuisine','cultural-awareness'],
    desc:'Cook several traditions with respect for what each is actually doing.' },
]);

addSkills({ cat: 'food', group: 'Drinks' }, [
  { id:'tea-coffee', name:'Tea & Coffee', tier:2, req:['measurement'],
    desc:'Grind, ratio, temperature and time — the difference between a drink and a habit.' },
  { id:'espresso', name:'Espresso Craft', tier:4, req:['tea-coffee','measurement'],
    desc:'Dose, distribution, pressure and dialling in a shot that changes daily.' },
  { id:'cocktails', name:'Cocktails', tier:3, req:['measurement','tasting'],
    desc:'Balance, dilution and technique across the dozen drinks everything else derives from.' },
  { id:'wine', name:'Wine Literacy', tier:4, req:['tasting','geography-literacy'],
    desc:'Grape, region and style — order and pair confidently without performing.' },
  { id:'tasting', name:'Tasting & Palate', tier:3, req:['seasoning','observation'],
    desc:'Identify what you are tasting and describe it in words another person can use.' },
  { id:'brewing', name:'Brewing Beer & Cider', tier:4, req:['fermenting','measurement'],
    desc:'Mash, boil, pitch and condition — fermentation with sanitation discipline.' },
  { id:'spirits', name:'Spirits & Distillates', tier:5, req:['wine','tasting'],
    desc:'Production methods and regional styles, and what age statements really tell you.' },
]);

addSkills({ cat: 'food', group: 'Eating Well' }, [
  { id:'label-reading', name:'Reading Food Labels', tier:1,
    desc:'Ingredients by weight, per-100g, and the marketing on the front of the packet.' },
  { id:'nutrition', name:'Nutrition & Meal Planning', tier:2, req:['cooking-basics'],
    desc:'Feed yourself well on a plan, a budget and a real schedule.' },
  { id:'macros', name:'Macronutrients & Energy', tier:3, req:['nutrition','numeracy'],
    desc:'Protein, carbohydrate, fat and calories understood well enough to steer by.' },
  { id:'meal-prep', name:'Meal Prep', tier:3, req:['nutrition','freezing','time-management'],
    desc:'A weekly routine that makes eating well the path of least resistance.' },
  { id:'food-budgeting', name:'Eating Well on a Budget', tier:3, req:['nutrition','budgeting'],
    desc:'Seasonal, staple-based cooking that is cheaper and better than the alternative.' },
  { id:'sports-nutrition', name:'Nutrition for Training', tier:4, req:['macros','program-design'],
    desc:'Timing, protein and fuelling for the training you are actually doing.' },
  { id:'special-diets', name:'Cooking for Dietary Needs', tier:4, req:['nutrition','allergy-management'],
    desc:'Cook well for coeliac, vegan, diabetic or allergic guests without a separate meal.' },
  { id:'nutrition-scepticism', name:'Reading Nutrition Claims', tier:4, req:['macros','medical-research'],
    desc:'Tell a finding from a headline, and a supplement from a solution.' },
  { id:'eating-habits', name:'Changing How You Eat', tier:5, req:['meal-prep','habits','nutrition-scepticism'],
    desc:'Shift a long-standing pattern of eating and hold it for years.' },
]);

addSkills({ cat: 'food', group: 'Shopping & Hosting' }, [
  { id:'grocery-shopping', name:'Grocery Shopping', tier:2, req:['price-awareness','nutrition'],
    desc:'A list, a route, and knowing what is worth paying more for.' },
  { id:'produce-selection', name:'Choosing Produce', tier:3, req:['grocery-shopping','observation'],
    desc:'Ripeness, freshness and season — picking the good one by feel and smell.' },
  { id:'butchery-fishmonger', name:'Buying Meat & Fish', tier:4, req:['produce-selection','meat-cookery'],
    desc:'Cuts, freshness, provenance, and asking a counter for what you actually need.' },
  { id:'menu-planning', name:'Planning a Menu', tier:4, req:['cooking-advanced','time-management'],
    desc:'Balance courses, oven space and your own time so it all lands together.' },
  { id:'dinner-party', name:'Cooking for Guests', tier:4, req:['menu-planning','hosting'],
    desc:'Feed eight people and still be in the room with them.' },
  { id:'cooking-at-scale', name:'Cooking for Fifty', tier:5, req:['dinner-party','operations','kitchen-hygiene'],
    desc:'Quantities, logistics and holding temperatures for a crowd.' },
  { id:'food-styling', name:'Food Photography & Styling', tier:4, req:['photo-basics','light-reading'],
    desc:'Make food look like itself on its best day, with real light.' },
  { id:'restaurant-work', name:'Professional Kitchen Skills', tier:5, req:['cooking-at-scale','stocks-sauces','operations'],
    desc:'Mise en place, service, speed and the discipline of a working line.' },
]);

addSkills({ cat: 'food', group: 'Food Knowledge' }, [
  { id:'food-history', name:'Food History & Geography', tier:3, req:['historical-context','geography-literacy'],
    desc:'Why a cuisine has the ingredients it has, and what arrived when.' },
  { id:'food-science', name:'Food Science', tier:4, req:['chemistry-basics','heat-control'],
    desc:'Emulsions, gluten, gelatinisation and Maillard — why techniques work.' },
  { id:'food-systems', name:'Where Food Comes From', tier:4, req:['ecology','economics-literacy'],
    desc:'Farming, supply chains, waste and the real cost behind a supermarket price.' },
  { id:'food-ethics', name:'Food Ethics', tier:5, req:['food-systems','ethical-framework'],
    desc:'Animals, labour, land and emissions weighed against what you actually eat.' },
  { id:'food-safety-management', name:'Food Safety Management', tier:5, req:['kitchen-hygiene','compliance','quality-systems'],
    desc:'HACCP, temperature logs and traceability for feeding the public legally.' },
]);

addSkills({ cat: 'food', group: 'More in the Kitchen' }, [
  { id:'soups-stews', name:'Soups & Stews', tier:2, req:['vegetables','seasoning'],
    desc:'Build depth from a base rather than relying on stock cubes at the end.' },
  { id:'salads-dressings', name:'Salads & Dressings', tier:2, req:['vegetables','seasoning'],
    desc:'Emulsify, balance acid and fat, and dress at the last possible moment.' },
  { id:'breakfast', name:'Breakfast Cookery', tier:2, req:['eggs','baking-basics'],
    desc:'Do the same handful of things extremely well before anyone is properly awake.' },
  { id:'sandwich-craft', name:'Sandwiches & Lunch', tier:2, req:['seasoning','food-storage'],
    desc:'Structure, moisture control and packing something that survives until one o’clock.' },
  { id:'condiments', name:'Making Condiments', tier:3, req:['seasoning','pickling'],
    desc:'Mayonnaise, hot sauce, chutney and stock — the things that improve everything else.' },
  { id:'cheese-dairy', name:'Cheese & Dairy', tier:4, req:['fermenting','tasting'],
    desc:'Make yoghurt and soft cheese, and buy, store and serve the rest properly.' },
  { id:'chocolate-sugar', name:'Chocolate & Sugar Work', tier:5, req:['desserts','measurement'],
    desc:'Tempering, crystallisation and the temperatures that decide everything.' },
  { id:'ice-cream', name:'Frozen Desserts', tier:4, req:['desserts','food-science'],
    desc:'Fat, sugar and overrun balanced so it scoops instead of setting like a brick.' },
  { id:'kitchen-timing', name:'Timing a Whole Meal', tier:4, req:['menu-planning','heat-control'],
    desc:'Work backwards so five things are ready at once and nothing sits going cold.' },
  { id:'cooking-for-one', name:'Cooking for One', tier:2, req:['cooking-basics','leftovers'],
    desc:'Scale, shop and cook so eating alone is a pleasure rather than a compromise.' },
  { id:'kids-cooking', name:'Cooking With Children', tier:3, req:['cooking-basics','play-with-children'],
    desc:'Give them real jobs and accept the mess; the fastest route to a competent adult.' },
]);

addSkills({ cat: 'food', group: 'Eating Out & Away' }, [
  { id:'ordering-out', name:'Ordering in a Restaurant', tier:2, req:['recipe-reading','politeness'],
    desc:'Read a menu, ask the right question, and order what the kitchen is good at.' },
  { id:'tipping-service', name:'Service & Tipping', tier:3, req:['ordering-out','etiquette'],
    desc:'Local norms, when to complain, and how to be a guest staff are glad to see.' },
  { id:'takeaway-judgement', name:'Eating Convenience Food Well', tier:2, req:['label-reading','nutrition'],
    desc:'Choose the takeaway or the ready meal that is not actively working against you.' },
  { id:'packed-lunch', name:'Food to Take With You', tier:2, req:['sandwich-craft','food-storage'],
    desc:'Portable food that survives a bag and beats whatever is near the office.' },
  { id:'camp-food-planning', name:'Food for a Trip', tier:3, req:['camp-cooking','packing'],
    desc:'Calories per gram, no fridge, and meals you still want to eat on day five.' },
  { id:'feeding-a-crowd-cheaply', name:'Feeding Many on Little', tier:5, req:['food-budgeting','cooking-at-scale'],
    desc:'Pulses, grains and one good sauce — dignity and flavour at very low cost per head.' },
]);

addSkills({ cat: 'food', group: 'Getting Confident' }, [
  { id:'boiling-toasting', name:'The First Ten Things', tier:1,
    desc:'Pasta, rice, eggs, toast and a stir-fry — food you can make hungry and tired.' },
  { id:'shopping-list', name:'Cooking From a Short List', tier:1,
    desc:'Ten ingredients that combine into a week of different meals.' },
  { id:'tasting-as-you-go', name:'Tasting As You Cook', tier:1,
    desc:'The habit that separates people who can cook from people who follow recipes.' },
  { id:'washing-veg', name:'Prep Basics', tier:1,
    desc:'Wash, peel, trim and store so cooking starts rather than begins with a fight.' },
  { id:'reading-a-dish', name:'Reverse-Engineering a Dish', tier:4, req:['tasting','flavour-pairing'],
    desc:'Eat something good and work out how to make a version of it at home.' },
  { id:'cooking-confidence', name:'Cooking Without Anxiety', tier:3, req:['tasting-as-you-go','heat-control','seasoning'],
    desc:'Trust your palate and your timing enough to stop needing the recipe open.' },
]);
