/* ==================================================================
   Mind & Character — attention, emotion, judgement, and who you are
   when nobody is checking.
================================================================== */

addSkills({ cat: 'mind', group: 'Self-Knowledge' }, [
  { id:'self-awareness', name:'Self-Awareness', tier:1,
    desc:'Notice what you are feeling and doing while you are doing it.' },
  { id:'body-signals', name:'Reading Your Own Body', tier:1,
    desc:'Tell hunger from boredom, tiredness from low mood, tension from fear.' },
  { id:'value-naming', name:'Naming What You Want', tier:1,
    desc:'Say plainly what you actually want out of a day, a job or a friendship.' },
  { id:'self-honesty', name:'Self-Honesty', tier:2, req:['self-awareness'],
    desc:'Catch the story you are telling yourself and check it against the evidence.' },
  { id:'trigger-mapping', name:'Knowing Your Triggers', tier:2, req:['self-awareness','body-signals'],
    desc:'Predict the situations that reliably make you reactive, and plan around them.' },
  { id:'strengths-audit', name:'Strengths & Weaknesses Audit', tier:2, req:['self-honesty'],
    desc:'An accurate, unflattering, unashamed inventory of what you are good at.' },
  { id:'inner-critic', name:'Working With the Inner Critic', tier:3, req:['self-honesty','emotion-regulation'],
    desc:'Use self-criticism as data without letting it run the whole room.' },
  { id:'shadow-work', name:'Facing What You Avoid', tier:4, req:['inner-critic','trigger-mapping'],
    desc:'Turn toward the traits, memories and fears you have been routing around.' },
  { id:'self-concept', name:'A Stable Self-Concept', tier:4, req:['strengths-audit','resilience'],
    desc:'Know who you are steadily enough that praise and criticism do not redefine you.' },

  /* --- rest & regulation --- */
]);

addSkills({ cat: 'mind', group: 'Rest & Regulation' }, [
  { id:'sleep', name:'Sleep Hygiene', tier:1,
    desc:'Consistent, sufficient sleep — the substrate everything else runs on.' },
  { id:'breathing', name:'Breathing & Calming', tier:1,
    desc:'Down-regulate your own nervous system on demand.' },
  { id:'rest-taking', name:'Actually Resting', tier:1,
    desc:'Stop without guilt, and rest in a way that restores rather than numbs.' },
  { id:'boredom-tolerance', name:'Tolerating Boredom', tier:2, req:['rest-taking'],
    desc:'Sit in an unstimulated moment without reaching for a screen.' },
  { id:'sleep-debugging', name:'Fixing Bad Sleep', tier:2, req:['sleep','body-signals'],
    desc:'Diagnose insomnia, light, caffeine, timing and anxiety as separate causes.' },
  { id:'nervous-system', name:'Nervous System Literacy', tier:3, req:['breathing','trigger-mapping'],
    desc:'Recognise fight, flight, freeze and shutdown in yourself and choose a way down.' },
  { id:'restorative-practice', name:'Restorative Practice', tier:3, req:['rest-taking','breathing'],
    desc:'A deliberate weekly ritual — sabbath, long walk, digital fast — that you keep.' },
  { id:'recovery-cycles', name:'Work–Recovery Cycling', tier:4, req:['nervous-system','focus'],
    desc:'Alternate intensity and recovery on purpose instead of grinding to a stop.' },
]);

addSkills({ cat: 'mind', group: 'Attention' }, [
  { id:'single-tasking', name:'Single-Tasking', tier:1,
    desc:'Do one thing at a time and finish it before opening the next.' },
  { id:'attention-hygiene', name:'Attention Hygiene', tier:2, req:['single-tasking'],
    desc:'Strip notifications, tabs and ambient pings out of your working environment.' },
  { id:'focus', name:'Focus & Deep Work', tier:2, req:['sleep','time-management'],
    desc:'Sustain uninterrupted attention on hard work for hours.' },
  { id:'flow', name:'Finding Flow', tier:3, req:['focus','single-tasking'],
    desc:'Match challenge to skill deliberately so absorbed work becomes repeatable.' },
  { id:'distraction-recovery', name:'Recovering From Interruption', tier:3, req:['attention-hygiene','focus'],
    desc:'Get back into deep context in minutes rather than losing the afternoon.' },
  { id:'context-switching', name:'Context Switching', tier:3, req:['focus','time-management'],
    desc:'Move between unrelated demanding tasks without dragging residue between them.' },
  { id:'deep-work-system', name:'A Deep Work System', tier:4, req:['flow','distraction-recovery','discipline'],
    desc:'Protected hours, a shutdown ritual and a defended calendar that actually hold.' },
]);

addSkills({ cat: 'mind', group: 'Habits & Will' }, [
  { id:'gratitude', name:'Gratitude Practice', tier:1,
    desc:'Deliberately attend to what is going right; a trainable default.' },
  { id:'starting', name:'Starting Things', tier:1,
    desc:'Beat the activation barrier: begin badly, on time, without a run-up.' },
  { id:'habits', name:'Habit Formation', tier:2, req:['routine','self-awareness'],
    desc:'Design cues, friction and rewards so behaviour runs without willpower.' },
  { id:'procrastination', name:'Beating Procrastination', tier:2, req:['starting','self-honesty'],
    desc:'Identify which of avoidance, ambiguity or fear is stopping you, and treat that.' },
  { id:'habit-breaking', name:'Breaking a Habit', tier:3, req:['habits','trigger-mapping'],
    desc:'Remove a compulsive behaviour by attacking its cue and reward, not your character.' },
  { id:'discipline', name:'Discipline', tier:3, req:['habits','focus'],
    desc:'Do the thing when it is boring, hard, and no one is watching.' },
  { id:'delayed-gratification', name:'Delayed Gratification', tier:3, req:['discipline','procrastination'],
    desc:'Reliably choose the larger later reward over the smaller sooner one.' },
  { id:'consistency', name:'Consistency Over Intensity', tier:4, req:['discipline','goal-setting'],
    desc:'Keep a practice alive across years, illness, moves and motivation troughs.' },
  { id:'self-control', name:'Impulse Control', tier:4, req:['delayed-gratification','emotion-regulation'],
    desc:'Put a real gap between the urge and the action, every time it matters.' },
]);

addSkills({ cat: 'mind', group: 'Emotion' }, [
  { id:'emotion-naming', name:'Naming Emotions', tier:1,
    desc:'Distinguish anger from hurt, anxiety from excitement, sadness from tiredness.' },
  { id:'emotion-regulation', name:'Emotional Regulation', tier:2, req:['self-awareness','breathing'],
    desc:'Feel it fully and still choose your response.' },
  { id:'sitting-with-feeling', name:'Sitting With Discomfort', tier:2, req:['emotion-naming','breathing'],
    desc:'Let an unpleasant feeling run its course without fixing, fleeing or numbing.' },
  { id:'anger-work', name:'Working With Anger', tier:3, req:['emotion-regulation','trigger-mapping'],
    desc:'Use anger as information about a violated boundary rather than as a weapon.' },
  { id:'anxiety-skills', name:'Managing Anxiety', tier:3, req:['sitting-with-feeling','nervous-system'],
    desc:'Exposure, cognitive reframing and physiology — the practical anti-anxiety toolkit.' },
  { id:'grief', name:'Grieving Well', tier:3, req:['sitting-with-feeling','emotion-regulation'],
    desc:'Move through loss without rushing it or getting permanently stuck in it.' },
  { id:'shame-resilience', name:'Shame Resilience', tier:4, req:['inner-critic','grief'],
    desc:'Recognise shame, say it out loud to someone safe, and refuse its conclusions.' },
  { id:'joy', name:'Capacity for Joy', tier:4, req:['gratitude','sitting-with-feeling'],
    desc:'Let good things land fully instead of bracing against their ending.' },
  { id:'equanimity', name:'Equanimity', tier:5, req:['meditation','shame-resilience','joy'],
    desc:'Meet good and bad news with the same steadiness, without going numb to either.' },
]);

addSkills({ cat: 'mind', group: 'Contemplative Practice' }, [
  { id:'stillness', name:'Sitting Still', tier:1,
    desc:'Stay put and quiet for ten minutes without needing it to be productive.' },
  { id:'meditation', name:'Meditation', tier:3, req:['breathing','focus'],
    desc:'A sustained practice of watching your own mind without grabbing at it.' },
  { id:'body-scan', name:'Body Awareness Practice', tier:2, req:['stillness','body-signals'],
    desc:'Track sensation through the body deliberately; the entry point to most somatic work.' },
  { id:'mindful-daily', name:'Everyday Mindfulness', tier:3, req:['body-scan','single-tasking'],
    desc:'Bring full attention to washing up, walking and waiting, not just to the cushion.' },
  { id:'loving-kindness', name:'Compassion Practice', tier:3, req:['meditation','empathy'],
    desc:'Systematically cultivate goodwill — including toward people you dislike.' },
  { id:'retreat', name:'Silent Retreat', tier:4, req:['meditation','restorative-practice'],
    desc:'Multi-day silence and practice, and integrating what surfaces afterwards.' },
  { id:'contemplative-depth', name:'Deep Contemplative Practice', tier:5, req:['retreat','equanimity'],
    desc:'A practice mature enough to change how you see, not just how you feel.' },
]);

addSkills({ cat: 'mind', group: 'Thinking & Judgement' }, [
  { id:'growth-mindset', name:'Growth Mindset', tier:2, req:['self-awareness','gratitude'],
    desc:'Treat difficulty as information about method, not about your ceiling.' },
  { id:'bias-awareness', name:'Cognitive Bias Awareness', tier:3, req:['self-honesty','critical-reading'],
    desc:'Know your own confirmation bias, sunk costs and hindsight, and build around them.' },
  { id:'decision-making', name:'Decision Making', tier:3, req:['focus','critical-reading'],
    desc:'Decide under uncertainty: expected value, reversibility, and your own biases.' },
  { id:'mental-models', name:'Mental Models', tier:3, req:['bias-awareness'],
    desc:'A working stock of transferable models — incentives, feedback loops, base rates.' },
  { id:'probabilistic-thinking', name:'Probabilistic Thinking', tier:4, req:['decision-making','statistics'],
    desc:'Hold degrees of belief, update on evidence, and stop needing certainty to act.' },
  { id:'forecasting', name:'Forecasting', tier:4, req:['probabilistic-thinking','bias-awareness'],
    desc:'Make calibrated numeric predictions and score yourself against reality.' },
  { id:'first-principles', name:'First-Principles Thinking', tier:4, req:['mental-models','logic'],
    desc:'Strip a problem back to what is actually true and rebuild from there.' },
  { id:'metacognition', name:'Metacognition', tier:4, req:['decision-making','study-systems'],
    desc:'Think about your own thinking: know what you know and how you learn.' },
  { id:'systems-thinking', name:'Systems Thinking', tier:4, req:['mental-models','feedback'],
    desc:'See stocks, flows, delays and loops instead of a chain of single causes.' },
  { id:'strategic-thinking', name:'Strategic Thinking', tier:5, req:['systems-thinking','forecasting','goal-setting'],
    desc:'Choose where to compete and what to give up, several moves ahead.' },
  { id:'judgement', name:'Judgement Under Uncertainty', tier:5, req:['probabilistic-thinking','first-principles','metacognition'],
    desc:'Consistently good calls on messy, underspecified, high-stakes questions.' },
]);

addSkills({ cat: 'mind', group: 'Resilience' }, [
  { id:'resilience', name:'Resilience', tier:3, req:['emotion-regulation','growth-mindset'],
    desc:'Absorb failure, loss and setback and keep functioning and learning.' },
  { id:'failure-processing', name:'Learning From Failure', tier:3, req:['growth-mindset','self-honesty'],
    desc:'Run an honest post-mortem on your own mistakes without self-flagellation.' },
  { id:'stress-management', name:'Stress & Burnout Management', tier:4, req:['resilience','meditation'],
    desc:'Recognise load early and change the system before it breaks you.' },
  { id:'adversity', name:'Handling Real Adversity', tier:4, req:['resilience','grief'],
    desc:'Illness, redundancy, betrayal, bereavement — carrying on while genuinely hurt.' },
  { id:'uncertainty-tolerance', name:'Tolerating Uncertainty', tier:4, req:['sitting-with-feeling','probabilistic-thinking'],
    desc:'Function well while a big open question stays open for months.' },
  { id:'antifragility', name:'Getting Stronger From Stress', tier:5, req:['adversity','failure-processing','stress-management'],
    desc:'Build a life whose setbacks reliably leave you more capable than before.' },
]);

addSkills({ cat: 'mind', group: 'Character & Direction' }, [
  { id:'honesty', name:'Everyday Honesty', tier:1,
    desc:'Say true things, including inconvenient ones, as your default setting.' },
  { id:'promise-keeping', name:'Keeping Your Word', tier:2, req:['honesty','time-awareness'],
    desc:'Only commit to what you will do, then do it — the root of being trusted.' },
  { id:'courage', name:'Ordinary Courage', tier:3, req:['assertive','sitting-with-feeling'],
    desc:'Do the right and uncomfortable thing while afraid — speak up, own up, step in.' },
  { id:'integrity', name:'Integrity', tier:4, req:['promise-keeping','courage'],
    desc:'The same person in private, under pressure, and when it costs you something.' },
  { id:'humility', name:'Intellectual Humility', tier:4, req:['bias-awareness','feedback'],
    desc:'Change your mind publicly when the evidence turns, without losing your nerve.' },
  { id:'goal-setting', name:'Long-Term Goal Setting', tier:4, req:['discipline','project-planning'],
    desc:'Set multi-year goals and reduce them to what you do this week.' },
  { id:'life-design', name:'Designing a Life', tier:5, req:['goal-setting','purpose','decision-making'],
    desc:'Choose work, place and people on purpose rather than by drift and default.' },
  { id:'wisdom', name:'Perspective & Wisdom', tier:5, req:['metacognition','stress-management'],
    desc:'Judgement that holds up across time, domains and other people’s lives.' },
  { id:'purpose', name:'Purpose & Values', tier:5, req:['goal-setting','metacognition'],
    desc:'Know what you are for, and let it decide what you say no to.' },
  { id:'self-mastery', name:'Self-Mastery', tier:5, req:['wisdom','purpose','discipline'],
    desc:'Your behaviour, attention and values reliably point the same direction.' },
]);

addSkills({ cat: 'mind', group: 'Motivation & Drive' }, [
  { id:'intrinsic-motivation', name:'Finding Intrinsic Motivation', tier:3, req:['value-naming','self-honesty'],
    desc:'Locate the version of a task you would do anyway, and lead with that.' },
  { id:'momentum', name:'Building Momentum', tier:2, req:['starting','habits'],
    desc:'Use small early wins deliberately to make the next action cheaper.' },
  { id:'accountability', name:'Using Accountability', tier:3, req:['promise-keeping','asking'],
    desc:'Put a person or a stake behind an intention so it stops being optional.' },
  { id:'motivation-troughs', name:'Working Through a Trough', tier:4, req:['consistency','intrinsic-motivation'],
    desc:'Keep going through the long middle where it is dull and nothing is visible.' },
  { id:'ambition-calibration', name:'Calibrating Ambition', tier:4, req:['goal-setting','self-honesty'],
    desc:'Aim high enough to stretch and low enough to finish, and know which you are doing.' },
  { id:'quitting-well', name:'Quitting Well', tier:4, req:['decision-making','sunk-cost'],
    desc:'Stop something that is not working, on purpose, without calling it failure.' },
  { id:'sunk-cost', name:'Escaping Sunk Costs', tier:3, req:['bias-awareness','self-honesty'],
    desc:'Judge from here forward, ignoring what it already cost you to get here.' },
]);

addSkills({ cat: 'mind', group: 'Creativity of Mind' }, [
  { id:'idea-capture', name:'Capturing Ideas', tier:1,
    desc:'Write it down within thirty seconds, always, in one place you will look again.' },
  { id:'divergent-thinking', name:'Divergent Thinking', tier:3, req:['idea-capture','questioning'],
    desc:'Generate twenty options before evaluating any of them.' },
  { id:'analogy', name:'Thinking by Analogy', tier:3, req:['mental-models','divergent-thinking'],
    desc:'Import a solved structure from somewhere else and test where the mapping breaks.' },
  { id:'constraint-use', name:'Using Constraints', tier:4, req:['divergent-thinking','first-principles'],
    desc:'Impose an artificial limit to force a better answer than open-endedness gives.' },
  { id:'incubation', name:'Letting Problems Incubate', tier:3, req:['rest-taking','divergent-thinking'],
    desc:'Load the problem, walk away deliberately, and be ready when it resolves.' },
  { id:'creative-confidence', name:'Creative Confidence', tier:4, req:['divergent-thinking','shame-resilience'],
    desc:'Produce and share rough work without needing it to be good first.' },
]);

addSkills({ cat: 'mind', group: 'Memory & Cognition' }, [
  { id:'working-memory', name:'Managing Working Memory', tier:2, req:['single-tasking','notetaking'],
    desc:'Offload to paper so your head is free for the part that needs thinking.' },
  { id:'prospective-memory', name:'Remembering to Do Things', tier:2, req:['note-apps','habits'],
    desc:'External triggers for future intentions, because willpower does not remember.' },
  { id:'cognitive-load', name:'Managing Cognitive Load', tier:3, req:['working-memory','attention-hygiene'],
    desc:'Reduce simultaneous demands so hard thinking has room to happen.' },
  { id:'decision-fatigue', name:'Decision Fatigue', tier:3, req:['cognitive-load','habits'],
    desc:'Automate small choices to protect the capacity for the ones that matter.' },
  { id:'cognitive-ageing', name:'Keeping a Mind Sharp', tier:5, req:['longevity','lifelong-learning','social-support'],
    desc:'Exercise, sleep, hearing, learning and company — what actually protects cognition.' },
]);

addSkills({ cat: 'mind', group: 'Ethics in Practice' }, [
  { id:'moral-intuition', name:'Trusting & Testing Moral Intuition', tier:3, req:['self-awareness','fallacies'],
    desc:'Take the gut reaction seriously as evidence, then interrogate it.' },
  { id:'moral-courage', name:'Doing the Unpopular Right Thing', tier:5, req:['courage','integrity','ethical-framework'],
    desc:'Act on your conclusion when the room, the boss and your interest all disagree.' },
  { id:'ethical-dilemmas', name:'Working Through Dilemmas', tier:4, req:['moral-intuition','decision-making'],
    desc:'Choose between two goods or two harms and be able to explain why.' },
  { id:'moral-repair', name:'Making Amends', tier:4, req:['apologising','integrity'],
    desc:'Do the actual restitution, not just the apology, and change the conditions.' },
  { id:'complicity', name:'Recognising Complicity', tier:5, req:['ethical-dilemmas','systems-thinking'],
    desc:'See where your ordinary participation sustains something you object to.' },
]);

addSkills({ cat: 'mind', group: 'Everyday Practices' }, [
  { id:'reflection', name:'Daily Reflection', tier:1,
    desc:'Two minutes at the end of the day on what went well and what you would change.' },
  { id:'noticing-mood', name:'Noticing Your Mood', tier:1,
    desc:'Check in with yourself before it becomes obvious to everyone else.' },
  { id:'saying-thank-you', name:'Expressing Gratitude', tier:2, req:['gratitude','honesty'],
    desc:'Tell the specific person the specific thing, out loud or in writing.' },
  { id:'asking-for-time', name:'Buying Yourself Time', tier:2, req:['self-awareness','assertive'],
    desc:'Say "let me think about that" instead of answering while activated.' },
  { id:'worry-time', name:'Containing Worry', tier:3, req:['anxiety-skills','routine-design'],
    desc:'Give anxiety a scheduled slot so it stops colonising the whole day.' },
  { id:'expectation-management', name:'Managing Your Own Expectations', tier:4, req:['ambition-calibration','probabilistic-thinking'],
    desc:'Predict outcomes honestly so disappointment stops being the default experience.' },
  { id:'comparison', name:'Not Comparing', tier:4, req:['self-concept','algorithm-awareness'],
    desc:'Notice the comparison, name the sample bias, and go back to your own scoreboard.' },
  { id:'perfectionism', name:'Beating Perfectionism', tier:4, req:['shame-resilience','quitting-well'],
    desc:'Ship it at good enough and treat the remaining ten percent as optional.' },
]);

addSkills({ cat: 'mind', group: 'Relating to Yourself' }, [
  { id:'self-compassion', name:'Self-Compassion', tier:3, req:['inner-critic','loving-kindness'],
    desc:'Speak to yourself the way you would to a friend in the same situation.' },
  { id:'identity-flexibility', name:'Holding Identity Loosely', tier:5, req:['self-concept','unlearning'],
    desc:'Change your mind, job or beliefs without it constituting an existential crisis.' },
  { id:'ageing-mind', name:'Ageing With Grace', tier:5, req:['mortality','equanimity','identity-flexibility'],
    desc:'Meet decline, irrelevance and loss of role without bitterness.' },
  { id:'loneliness', name:'Handling Loneliness', tier:4, req:['solitude','help-seeking','making-friends'],
    desc:'Tell solitude from loneliness and act on the second rather than enduring it.' },
  { id:'envy', name:'Working With Envy', tier:4, req:['comparison','self-honesty'],
    desc:'Read envy as information about what you want, then do something about it.' },
  { id:'boredom-as-signal', name:'Reading Boredom', tier:3, req:['boredom-tolerance','value-naming'],
    desc:'Tell "this is beneath me" from "I am avoiding this" from "this is genuinely wrong".' },
]);
