/* ==================================================================
   Sports & Movement — what the body can be trained to do.
================================================================== */

addSkills({ cat: 'physical', group: 'Movement Foundations' }, [
  { id:'posture', name:'Posture & Walking Gait', tier:1,
    desc:'Stand, sit and walk in alignment — the base every other movement loads onto.' },
  { id:'coordination', name:'Basic Coordination', tier:1,
    desc:'Throw, catch, jump, change direction; hands and eyes working together.' },
  { id:'bodyweight', name:'Bodyweight Basics', tier:1,
    desc:'Squat, hinge, push and pull your own bodyweight with control.' },
  { id:'balance', name:'Balance', tier:1,
    desc:'Single-leg stability, recovering a stumble, staying upright on uneven ground.' },
  { id:'falling', name:'Falling Safely', tier:2, req:['balance','coordination'],
    desc:'Tuck, roll and spread the impact instead of landing on a wrist.' },
  { id:'agility', name:'Balance & Agility', tier:2, req:['coordination'],
    desc:'Accelerate, stop, pivot and stay upright under pressure.' },
  { id:'mobility', name:'Flexibility & Mobility', tier:3, req:['posture'],
    desc:'Full usable range of motion; the thing that keeps the others injury-free.' },
  { id:'proprioception', name:'Body Control in Space', tier:3, req:['balance','agility'],
    desc:'Know where your limbs are without looking — the base of every technical sport.' },
  { id:'hand-eye', name:'Advanced Hand-Eye Coordination', tier:3, req:['coordination','proprioception'],
    desc:'Track and intercept a fast-moving object reliably under pressure.' },
]);

addSkills({ cat: 'physical', group: 'Endurance' }, [
  { id:'walking-fitness', name:'Walking Fitness', tier:1,
    desc:'Comfortably cover ten kilometres on foot in a day without wrecking yourself.' },
  { id:'running', name:'Running Base', tier:2, req:['posture','bodyweight'],
    desc:'Run 5 km at conversational pace with sustainable form.' },
  { id:'cycling', name:'Cycling', tier:2, req:['coordination','posture'],
    desc:'Ride confidently in traffic and over distance; basic bike handling.' },
  { id:'rowing', name:'Rowing & Ergometer', tier:2, req:['bodyweight','posture'],
    desc:'The hinge-drive sequence that makes rowing a full-body engine rather than a back injury.' },
  { id:'aerobic-base', name:'Aerobic Base Building', tier:3, req:['running'],
    desc:'Zone-2 volume, heart-rate discipline, and the patience it demands.' },
  { id:'distance-running', name:'Distance Running', tier:3, req:['running'],
    desc:'Half-marathon capable: pacing, fuelling, weekly mileage structure.' },
  { id:'hill-running', name:'Hills & Trail Running', tier:3, req:['running','proprioception'],
    desc:'Climb, descend and read technical ground without turning an ankle.' },
  { id:'interval-training', name:'Interval & Threshold Training', tier:3, req:['aerobic-base','numeracy'],
    desc:'Structure hard sessions by pace, power or heart rate rather than by feel.' },
  { id:'marathon', name:'Marathon & Endurance', tier:4, req:['distance-running','mobility'],
    desc:'Train for and finish a marathon-distance event intact.' },
  { id:'ultra-endurance', name:'Ultra Endurance', tier:5, req:['marathon','hill-running','recovery-protocol'],
    desc:'Move for eight hours or more: fuelling, feet, night, and the mental collapse.' },
  { id:'triathlon', name:'Multi-Sport Endurance', tier:4, req:['swim-strokes','cycling','distance-running'],
    desc:'Swim, bike and run back to back — triathlon-ready conditioning.' },
]);

addSkills({ cat: 'physical', group: 'Strength & Power' }, [
  { id:'strength', name:'Strength Training', tier:2, req:['bodyweight'],
    desc:'Progressive overload with free weights and a program you stick to.' },
  { id:'core-strength', name:'Core & Trunk Strength', tier:2, req:['bodyweight','posture'],
    desc:'Brace, anti-rotate and transfer force through the middle without collapsing.' },
  { id:'grip-strength', name:'Grip Strength', tier:2, req:['bodyweight'],
    desc:'Hold on — carries, hangs and pulls that stop being limited by your hands.' },
  { id:'calisthenics', name:'Calisthenics', tier:3, req:['bodyweight','core-strength'],
    desc:'Pull-ups, dips, levers and handstands — strength expressed through your own body.' },
  { id:'weightlifting', name:'Weightlifting Technique', tier:3, req:['strength'],
    desc:'Heavy squat, deadlift, press and bench with safe, repeatable form.' },
  { id:'kettlebells', name:'Kettlebell Training', tier:3, req:['strength','core-strength'],
    desc:'Swings, cleans and get-ups — ballistic strength in a very small space.' },
  { id:'plyometrics', name:'Plyometrics & Jumping', tier:3, req:['agility','strength'],
    desc:'Store and release elastic energy: jump higher, land softer, change direction faster.' },
  { id:'olympic-lift', name:'Olympic Lifting', tier:4, req:['weightlifting','mobility'],
    desc:'Snatch and clean-and-jerk — explosive strength under technical load.' },
  { id:'powerlifting', name:'Powerlifting', tier:4, req:['weightlifting','discipline'],
    desc:'Peak a squat, bench and deadlift total for a platform on a chosen date.' },
  { id:'gymnastics-strength', name:'Gymnastic Strength', tier:5, req:['calisthenics','mobility','proprioception'],
    desc:'Planche, front lever, ring work — strength at the edge of what bodies do.' },
]);

addSkills({ cat: 'physical', group: 'Water' }, [
  { id:'swim-basics', name:'Water Confidence', tier:1,
    desc:'Float, breathe and move safely in deep water.' },
  { id:'treading-water', name:'Treading Water & Survival Float', tier:2, req:['swim-basics'],
    desc:'Stay up, calm and breathing for a long time without a flotation aid.' },
  { id:'swim-strokes', name:'Swimming Strokes', tier:3, req:['swim-basics','bodyweight'],
    desc:'Efficient freestyle plus one other stroke over sustained distance.' },
  { id:'open-water', name:'Open-Water Swimming', tier:4, req:['swim-strokes','treading-water'],
    desc:'Cold, chop, sighting and no black line — swimming where there are no walls.' },
  { id:'diving-skill', name:'Diving & Entries', tier:3, req:['swim-strokes','proprioception'],
    desc:'Enter the water cleanly from a block or a height without hurting yourself.' },
  { id:'snorkelling', name:'Snorkelling & Freediving Basics', tier:3, req:['treading-water','breathing'],
    desc:'Equalise, duck-dive and stay relaxed under the surface on one breath.' },
  { id:'scuba', name:'Scuba Diving', tier:4, req:['snorkelling','swim-strokes','risk-assessment'],
    desc:'Certified diving: gas planning, buoyancy, buddy procedure and emergency ascent.' },
  { id:'surfing', name:'Surfing', tier:4, req:['open-water','balance','proprioception'],
    desc:'Read a break, paddle into a wave, pop up and ride it under control.' },
  { id:'paddling', name:'Kayaking & Paddling', tier:3, req:['treading-water','core-strength'],
    desc:'Forward stroke, edging and a wet exit — moving a boat where you intend.' },
  { id:'sailing', name:'Sailing', tier:4, req:['paddling','navigation','weather-reading'],
    desc:'Points of sail, trim, tacking and taking a small boat out and back.' },
  { id:'lifesaving', name:'Water Rescue & Lifesaving', tier:5, req:['open-water','first-aid','treading-water'],
    desc:'Reach, throw, tow and resuscitate — pulling someone out without becoming a second casualty.' },
]);

addSkills({ cat: 'physical', group: 'Team Sports' }, [
  { id:'ball-sports', name:'Ball Sport Fundamentals', tier:3, req:['agility','coordination'],
    desc:'Core technique in a sport — football, basketball, tennis, cricket.' },
  { id:'football', name:'Football', tier:3, req:['ball-sports'],
    desc:'First touch, passing, movement off the ball, and defending as a unit.' },
  { id:'basketball', name:'Basketball', tier:3, req:['ball-sports','plyometrics'],
    desc:'Handle, shoot, rebound and read a pick-and-roll from either side.' },
  { id:'cricket-baseball', name:'Cricket & Baseball Skills', tier:3, req:['ball-sports','hand-eye'],
    desc:'Bat, bowl or pitch, and field — striking and catching a small hard ball.' },
  { id:'rugby-contact', name:'Contact Field Sports', tier:4, req:['ball-sports','strength','falling'],
    desc:'Tackle, ruck and carry safely in a full-contact game.' },
  { id:'volleyball', name:'Volleyball & Net Games', tier:3, req:['ball-sports','plyometrics'],
    desc:'Pass, set, spike, block — and the rotations that make them work.' },
  { id:'hockey-stick', name:'Stick & Puck Sports', tier:4, req:['ball-sports','proprioception'],
    desc:'Field or ice hockey, lacrosse — controlling a ball or puck at the end of a stick.' },
  { id:'team-strategy', name:'Team Sport Strategy', tier:4, req:['ball-sports','conversation'],
    desc:'Read a game, hold a position, and communicate on the pitch.' },
  { id:'captaincy', name:'Captaincy', tier:5, req:['team-strategy','leadership'],
    desc:'Set the tone, make in-game calls, and hold a team together when losing.' },
]);

addSkills({ cat: 'physical', group: 'Racquet & Target' }, [
  { id:'racquet-basics', name:'Racquet Sport Basics', tier:2, req:['coordination'],
    desc:'Grip, footwork and a repeatable swing in tennis, badminton or squash.' },
  { id:'tennis', name:'Tennis', tier:3, req:['racquet-basics','agility'],
    desc:'Serve, groundstrokes, net play and constructing a point rather than hitting hard.' },
  { id:'table-tennis', name:'Table Tennis', tier:3, req:['racquet-basics','hand-eye'],
    desc:'Spin, placement and reading an opponent’s bat at very short reaction times.' },
  { id:'badminton-squash', name:'Badminton & Squash', tier:3, req:['racquet-basics','agility'],
    desc:'Court coverage, deception and the fitness these games quietly demand.' },
  { id:'golf', name:'Golf', tier:3, req:['coordination','proprioception'],
    desc:'A repeatable swing, short game, course management and your own temper.' },
  { id:'archery-shooting', name:'Archery & Target Shooting', tier:3, req:['breathing','proprioception'],
    desc:'Stance, sight picture, release and follow-through — plus absolute range discipline.' },
  { id:'darts-precision', name:'Precision Throwing Games', tier:2, req:['coordination'],
    desc:'Darts, bowls, pétanque — repeatable fine motor control under mild pressure.' },
]);

addSkills({ cat: 'physical', group: 'Combat Sports' }, [
  { id:'martial-arts', name:'Martial Arts', tier:4, req:['agility','strength'],
    desc:'Live sparring competence in a striking or grappling discipline.' },
  { id:'striking', name:'Striking Fundamentals', tier:3, req:['agility','core-strength'],
    desc:'Stance, guard, footwork, jab and cross — boxing or kickboxing basics.' },
  { id:'grappling', name:'Grappling Fundamentals', tier:3, req:['falling','core-strength'],
    desc:'Positions, escapes and submissions from wrestling, judo or jiu-jitsu.' },
  { id:'sparring', name:'Sparring', tier:4, req:['striking','grappling'],
    desc:'Work live against a resisting partner while staying technical and safe.' },
  { id:'self-defence', name:'Self-Defence', tier:4, req:['striking','situational-awareness'],
    desc:'Avoid, de-escalate, and if you must, create space and leave.' },
  { id:'fight-strategy', name:'Fight Strategy', tier:5, req:['sparring','forecasting'],
    desc:'Game-plan an opponent, adapt mid-fight, and manage rounds and energy.' },
]);

addSkills({ cat: 'physical', group: 'Wheels, Boards & Heights' }, [
  { id:'skating', name:'Skating', tier:3, req:['balance','falling'],
    desc:'Ice, roller or skateboard — glide, turn and stop with confidence.' },
  { id:'skiing', name:'Skiing & Snowboarding', tier:4, req:['balance','falling','proprioception'],
    desc:'Control speed and line on a red run, and read snow and avalanche warnings.' },
  { id:'mtb', name:'Mountain Biking', tier:4, req:['cycling','proprioception','falling'],
    desc:'Descend technical trail, pick a line, and repair a bike in the woods.' },
  { id:'climbing-indoor', name:'Indoor Climbing', tier:3, req:['grip-strength','core-strength'],
    desc:'Movement, footwork and belaying safely on a bouldering or lead wall.' },
  { id:'climbing-outdoor', name:'Outdoor Rock Climbing', tier:5, req:['climbing-indoor','rope-work','risk-assessment'],
    desc:'Place gear, build anchors and lead real rock with a partner’s life on your system.' },
  { id:'parkour', name:'Parkour & Movement', tier:4, req:['plyometrics','falling','proprioception'],
    desc:'Vault, precision jump and roll through terrain rather than around it.' },
  { id:'horse-riding', name:'Horse Riding', tier:3, req:['balance','animal-handling'],
    desc:'Seat, aids and the trust it takes to work with a half-tonne animal.' },
]);

addSkills({ cat: 'physical', group: 'Dance & Expression' }, [
  { id:'rhythm-body', name:'Moving in Time', tier:1,
    desc:'Find the beat and move on it without thinking about it.' },
  { id:'social-dance', name:'Social Dancing', tier:2, req:['rhythm-body','body-language'],
    desc:'Lead or follow through a few partner dances well enough to enjoy a wedding.' },
  { id:'dance-technique', name:'Dance Technique', tier:3, req:['social-dance','mobility'],
    desc:'Line, turnout, extension and control in a formal discipline.' },
  { id:'choreography', name:'Choreography', tier:4, req:['dance-technique','composition'],
    desc:'Build a phrase, shape a piece in space and time, and teach it to bodies.' },
  { id:'performance-dance', name:'Performing Dance', tier:5, req:['choreography','stage-presence'],
    desc:'Deliver a piece to an audience with full commitment and no visible counting.' },
  { id:'yoga', name:'Yoga Practice', tier:3, req:['mobility','breathing'],
    desc:'A sustained asana and breath practice with sound alignment.' },
  { id:'martial-forms', name:'Forms & Kata', tier:3, req:['proprioception','discipline'],
    desc:'Tai chi, kata or capoeira sequences — precision movement held over years.' },
]);

addSkills({ cat: 'physical', group: 'Training & Coaching' }, [
  { id:'program-design', name:'Designing a Training Program', tier:4, req:['strength','interval-training','metacognition'],
    desc:'Volume, intensity, frequency and progression written down and adjusted honestly.' },
  { id:'peak-conditioning', name:'Peak Conditioning', tier:5, req:['marathon','olympic-lift'],
    desc:'Periodised training that peaks strength and endurance on a chosen date.' },
  { id:'competition', name:'Competitive Performance', tier:5, req:['team-strategy','martial-arts'],
    desc:'Perform at your ceiling when it is scored and someone is opposing you.' },
  { id:'sports-psychology', name:'Sports Psychology', tier:4, req:['emotion-regulation','flow'],
    desc:'Arousal control, routines and self-talk that survive the actual start line.' },
  { id:'athletic-coaching', name:'Athletic Coaching', tier:5, req:['team-strategy','mentoring'],
    desc:'Program, correct and motivate other athletes toward their own peak.' },
  { id:'officiating', name:'Refereeing & Officiating', tier:4, req:['team-strategy','conflict'],
    desc:'Know the laws cold and apply them consistently while everyone shouts at you.' },
]);

addSkills({ cat: 'physical', group: 'Track & Field' }, [
  { id:'sprinting', name:'Sprinting', tier:3, req:['plyometrics','running'],
    desc:'Start, drive phase and top-end mechanics — speed as a technical skill.' },
  { id:'middle-distance', name:'Middle-Distance Running', tier:4, req:['interval-training','sprinting'],
    desc:'Race tactics and the specific pain tolerance of 800m to 5000m.' },
  { id:'jumping-events', name:'Jumping Events', tier:4, req:['plyometrics','proprioception'],
    desc:'Long, high or triple jump — approach consistency and takeoff mechanics.' },
  { id:'throwing-events', name:'Throwing Events', tier:4, req:['olympic-lift','proprioception'],
    desc:'Shot, discus or javelin — sequencing power from the ground through the implement.' },
  { id:'hurdling', name:'Hurdling', tier:4, req:['sprinting','mobility'],
    desc:'Stride pattern, lead leg and rhythm that survives fatigue.' },
  { id:'race-walking', name:'Race Walking & Speed Hiking', tier:3, req:['walking-fitness','posture'],
    desc:'Efficient fast walking technique over long distances without breaking into a run.' },
]);

addSkills({ cat: 'physical', group: 'Training Science' }, [
  { id:'heart-rate-training', name:'Heart Rate & Zones', tier:3, req:['aerobic-base','measurement'],
    desc:'Establish your own zones and actually train in the one you intended.' },
  { id:'load-tracking', name:'Tracking Training Load', tier:4, req:['program-design','data-analysis'],
    desc:'Volume, intensity and acute-to-chronic ratio recorded honestly enough to be useful.' },
  { id:'periodisation', name:'Periodisation', tier:5, req:['program-design','goal-setting'],
    desc:'Blocks, tapers and peaking so the best day is the day of the event.' },
  { id:'strength-standards', name:'Assessing Physical Capacity', tier:3, req:['strength','measurement'],
    desc:'Test, benchmark and re-test so progress is a number rather than a feeling.' },
  { id:'movement-screening', name:'Movement Screening', tier:4, req:['mobility','injury-prevention'],
    desc:'Spot asymmetry and restriction before they become the injury.' },
  { id:'return-to-sport', name:'Returning After Injury', tier:5, req:['rehab','load-tracking','patience-craft'],
    desc:'Graded return that does not reinjure you in the third week back.' },
  { id:'altitude-heat', name:'Training in Heat & Altitude', tier:5, req:['periodisation','recovery-protocol'],
    desc:'Acclimatisation timelines and adjusting expectations to the environment.' },
]);

addSkills({ cat: 'physical', group: 'Other Sports' }, [
  { id:'bouldering', name:'Bouldering', tier:3, req:['climbing-indoor','plyometrics'],
    desc:'Reading a problem, body tension and committing to a dynamic move.' },
  { id:'orienteering', name:'Orienteering', tier:4, req:['hill-running','navigation'],
    desc:'Navigate accurately at speed with a heart rate that makes reading hard.' },
  { id:'fencing', name:'Fencing', tier:4, req:['agility','proprioception'],
    desc:'Distance, timing and the conversation of blade actions at high speed.' },
  { id:'gymnastics', name:'Gymnastics', tier:5, req:['gymnastics-strength','falling','proprioception'],
    desc:'Tumbling and apparatus work with air awareness and a coach who spots you.' },
  { id:'climbing-rope-skills', name:'Belaying & Rope Management', tier:3, req:['climbing-indoor','knots'],
    desc:'Catch, lower and manage a rope with someone’s life attached to your attention.' },
  { id:'winter-hillwalking', name:'Winter Hillwalking', tier:5, req:['hill-safety','cold-injury','skiing'],
    desc:'Ice axe, crampons and judgement about when the hill is simply not on.' },
  { id:'adaptive-sport', name:'Adaptive & Para Sport', tier:5, req:['program-design','disability-navigation'],
    desc:'Classification, equipment and training around a body that works differently.' },
  { id:'endurance-swim-run', name:'Multi-Discipline Events', tier:5, req:['triathlon','open-water','navigation'],
    desc:'Swimrun, adventure racing and events where the transitions are the difficulty.' },
]);

addSkills({ cat: 'physical', group: 'Everyday Movement' }, [
  { id:'active-transport', name:'Walking & Cycling Everywhere', tier:2, req:['walking-fitness','cycling'],
    desc:'Make transport the exercise, which is the only version that survives a busy year.' },
  { id:'carrying', name:'Carrying Things', tier:2, req:['core-strength','manual-handling'],
    desc:'Load, position and gait for shopping, children and awkward furniture.' },
  { id:'getting-up-down', name:'Floor Work', tier:3, req:['mobility','balance'],
    desc:'Get to the floor and back up without hands — a real predictor of later independence.' },
  { id:'stairs-hills', name:'Stairs & Gradients', tier:2, req:['walking-fitness'],
    desc:'Climb without dread, and descend without wrecking your knees.' },
  { id:'movement-snacks', name:'Movement Snacks', tier:2, req:['sitting-less','bodyweight'],
    desc:'Two minutes of something hard, several times a day, everywhere.' },
  { id:'exercise-habit', name:'Making Exercise Stick', tier:3, req:['movement-habit','habits','intrinsic-motivation'],
    desc:'Find the version you will still be doing in five years, not the optimal one.' },
]);

addSkills({ cat: 'physical', group: 'Sport in Life' }, [
  { id:'finding-a-sport', name:'Finding a Sport You Like', tier:2, req:['coordination','playfulness'],
    desc:'Try enough of them to find the one you would do without discipline.' },
  { id:'joining-a-club', name:'Joining a Sports Club', tier:3, req:['finding-a-sport','joining-a-group'],
    desc:'Turn up to a training session as a beginner and come back the next week.' },
  { id:'training-with-others', name:'Training With Other People', tier:3, req:['joining-a-club','accountability'],
    desc:'The single most reliable way to still be doing it in two years.' },
  { id:'sport-and-work', name:'Fitting Training Into Life', tier:4, req:['exercise-habit','calendar-discipline'],
    desc:'A weekly plan that survives a job, children and travel rather than assuming none.' },
  { id:'masters-sport', name:'Competing After Forty', tier:5, req:['program-design','recovery-protocol','ageing-mind'],
    desc:'Train around slower recovery and enjoy competing without the times you used to have.' },
  { id:'coaching-children', name:'Coaching Children', tier:5, req:['athletic-coaching','play-with-children','safeguarding'],
    desc:'Fun first, fundamentals second, winning a distant third.' },
]);
