/* ==================================================================
   Home & Practical — running a household, keeping it standing, and
   getting through a week without anything catching fire.
================================================================== */

addSkills({ cat: 'practical', group: 'Running Your Day' }, [
  { id:'time-awareness', name:'Time Awareness', tier:1,
    desc:'Estimate how long things take and reliably show up when you said you would.' },
  { id:'punctuality', name:'Punctuality', tier:2, req:['time-awareness'],
    desc:'Work backwards from the start time, including the bit everyone forgets.' },
  { id:'time-management', name:'Time Management', tier:2, req:['time-awareness','routine'],
    desc:'Calendar, task list and prioritisation that survive a busy week.' },
  { id:'calendar-discipline', name:'Calendar Discipline', tier:3, req:['time-management','note-apps'],
    desc:'One calendar, everything in it, defended — including the blank parts.' },
  { id:'errands', name:'Batching Errands', tier:2, req:['time-management'],
    desc:'Group the trivial tasks by place and mode so they cost one hour, not five.' },
  { id:'weekly-review', name:'A Weekly Review', tier:3, req:['calendar-discipline','note-apps'],
    desc:'Half an hour that clears the inbox, closes loops and sets the coming week.' },
  { id:'life-admin', name:'Life Admin', tier:3, req:['record-keeping','weekly-review'],
    desc:'Renewals, appointments, forms and bills handled before they become urgent.' },
]);

addSkills({ cat: 'practical', group: 'Keeping House' }, [
  { id:'home-care', name:'Home Care', tier:2, req:['routine'],
    desc:'Cleaning, laundry, and keeping a space livable without a crisis.' },
  { id:'cleaning-technique', name:'Cleaning Properly', tier:2, req:['home-care','household-chemistry'],
    desc:'Top down, right product, dwell time — cleaning that works rather than smells clean.' },
  { id:'laundry', name:'Laundry', tier:1,
    desc:'Sort, temperature, detergent and drying that does not shrink or grey everything.' },
  { id:'stain-removal', name:'Stain Removal', tier:3, req:['laundry','household-chemistry'],
    desc:'Identify the stain and treat it with the right thing before it sets.' },
  { id:'ironing', name:'Ironing & Pressing', tier:2, req:['laundry'],
    desc:'Shirt, trousers and a collar that looks like it came from somewhere good.' },
  { id:'decluttering', name:'Decluttering', tier:3, req:['home-care','decision-making'],
    desc:'Decide what leaves, where it goes, and stop it coming back in.' },
  { id:'storage-systems', name:'Storage & Organisation', tier:3, req:['decluttering'],
    desc:'A place for everything, chosen by how often you actually use it.' },
  { id:'cleaning-rota', name:'A Household Rota', tier:3, req:['cleaning-technique','shared-living'],
    desc:'Who does what, how often, agreed rather than resented.' },
  { id:'deep-clean', name:'Deep Cleaning', tier:3, req:['cleaning-technique'],
    desc:'Oven, limescale, grout, mattress — the twice-a-year jobs done properly.' },
  { id:'pest-control', name:'Pests & Damp', tier:3, req:['cleaning-technique','observation'],
    desc:'Identify moths, mice, mould or condensation and treat the cause, not the symptom.' },
]);

addSkills({ cat: 'practical', group: 'Home Maintenance' }, [
  { id:'home-systems', name:'Knowing Your Home', tier:2, req:['tool-handling'],
    desc:'Stopcock, fuse box, meter, boiler — where they are and what they do.' },
  { id:'repair', name:'Repair & Maintenance', tier:3, req:['home-care'],
    desc:'Fix the bike, the shelf, the tap — basic tools and the nerve to open things.' },
  { id:'painting-decorating', name:'Painting & Decorating', tier:3, req:['finishing','measuring-marking'],
    desc:'Prep, cut in and roll so it looks like a professional did it.' },
  { id:'plumbing-basics', name:'Basic Plumbing', tier:3, req:['home-systems','tool-handling'],
    desc:'Washers, traps, isolating valves and stopping a leak at two in the morning.' },
  { id:'electrical-basics', name:'Basic Electrics', tier:3, req:['electricity-basics','home-systems'],
    desc:'Sockets, fittings and testing — plus knowing exactly where to stop.' },
  { id:'carpentry-home', name:'Home Carpentry', tier:3, req:['woodwork-basics','measuring-marking'],
    desc:'Shelves, doors, skirting and flat-pack that ends up square and level.' },
  { id:'wall-fixings', name:'Fixing Things to Walls', tier:2, req:['tool-handling','measuring-marking'],
    desc:'Find the stud or the void, choose the right plug, and hang something heavy safely.' },
  { id:'tiling', name:'Tiling', tier:4, req:['measuring-marking','adhesives'],
    desc:'Set out from the centre, cut around obstacles and grout without a wavy line.' },
  { id:'flooring', name:'Flooring', tier:4, req:['carpentry-home','measuring-marking'],
    desc:'Subfloor, underlay, expansion gaps and a joint that does not lift in a year.' },
  { id:'insulation', name:'Insulation & Draughts', tier:4, req:['home-systems','energy-literacy'],
    desc:'Find where the heat leaves and fix it in order of cost per degree.' },
  { id:'heating-systems', name:'Heating & Ventilation', tier:4, req:['home-systems','fluid-power'],
    desc:'Bleed, balance, thermostats and why one room is always cold.' },
  { id:'roof-gutters', name:'Roof, Gutters & Exterior', tier:4, req:['ladder-safety','home-systems'],
    desc:'Clear, inspect and spot the small failure before it becomes a ceiling.' },
  { id:'ladder-safety', name:'Working at Height', tier:2, req:['workshop-safety'],
    desc:'Angle, footing, three points of contact, and knowing when to hire a scaffold.' },
  { id:'renovation', name:'Managing a Renovation', tier:5, req:['project-planning','trades-management','building-regs'],
    desc:'Sequence trades, control scope and finish within some relationship to the budget.' },
  { id:'trades-management', name:'Hiring Tradespeople', tier:4, req:['suppliers','contracts-reading'],
    desc:'Get comparable quotes, check credentials, and pay in stages against work done.' },
  { id:'building-regs', name:'Permissions & Building Rules', tier:4, req:['bureaucracy','legal-literacy'],
    desc:'Planning, regulations and party walls — what needs consent before you start.' },
]);

addSkills({ cat: 'practical', group: 'Utilities & Bills' }, [
  { id:'utilities-setup', name:'Setting Up Utilities', tier:2, req:['form-filling','bank-account'],
    desc:'Energy, water, broadband and council tax moved into your name without a gap.' },
  { id:'energy-literacy', name:'Energy Use & Bills', tier:3, req:['utilities-setup','numeracy'],
    desc:'Read a meter and a tariff, and know which appliances actually cost anything.' },
  { id:'bill-switching', name:'Switching Providers', tier:3, req:['energy-literacy','comparison-shopping'],
    desc:'Move supplier annually and never sit on a default tariff again.' },
  { id:'waste-recycling', name:'Waste & Recycling', tier:2, req:['home-care'],
    desc:'What goes where locally, and how to dispose of paint, batteries and a mattress.' },
  { id:'water-management', name:'Water & Drainage', tier:3, req:['plumbing-basics','waste-recycling'],
    desc:'Leaks, blockages, outside taps and what must never go down a drain.' },
]);

addSkills({ cat: 'practical', group: 'Housing Moves' }, [
  { id:'flat-hunting', name:'Finding Somewhere to Live', tier:3, req:['renting','geography-literacy'],
    desc:'Viewings, commute reality, noise, damp and asking the awkward questions.' },
  { id:'moving-house', name:'Moving House', tier:4, req:['project-planning','flat-hunting'],
    desc:'Boxes, dates, redirects and utilities so nothing is lost and nothing overlaps.' },
  { id:'house-share-admin', name:'Running a Shared House', tier:3, req:['shared-living','cleaning-rota','budgeting'],
    desc:'Bills, deposits and rotas set up so the household does not need a referee.' },
  { id:'home-security', name:'Home Security', tier:3, req:['threat-modelling','home-systems'],
    desc:'Locks, lighting, habits and what actually deters an opportunist.' },
  { id:'home-inventory', name:'Home Inventory & Contents Cover', tier:3, req:['record-keeping','insurance'],
    desc:'Know what you own and what it is worth before you have to claim for it.' },
]);

addSkills({ cat: 'practical', group: 'Stuff & Systems' }, [
  { id:'buying-secondhand', name:'Buying Second-Hand', tier:3, req:['comparison-shopping','negotiating-price'],
    desc:'Inspect, test, negotiate and avoid the listings that are obviously not real.' },
  { id:'selling-stuff', name:'Selling Your Things', tier:3, req:['buying-secondhand','photo-basics'],
    desc:'Photograph, price and describe so it sells the first weekend.' },
  { id:'gift-giving', name:'Giving Gifts Well', tier:3, req:['empathy','name-memory'],
    desc:'Pay attention all year and give something specific rather than expensive.' },
  { id:'wrapping', name:'Wrapping & Presentation', tier:2, req:['fine-motor','papercraft'],
    desc:'Sharp corners, ribbon and a card written before the day it is needed.' },
  { id:'appliance-choice', name:'Choosing Appliances', tier:3, req:['comparison-shopping','energy-literacy'],
    desc:'Repairability, running cost and lifespan over the feature list on the box.' },
  { id:'car-maintenance', name:'Car Maintenance', tier:3, req:['tool-handling','repair'],
    desc:'Tyres, fluids, bulbs and knowing what the warning light actually means.' },
  { id:'bike-maintenance', name:'Bike Maintenance', tier:2, req:['tool-handling'],
    desc:'Puncture, brakes, gears and chain — keeping a bike safe and quiet.' },
  { id:'sustainable-home', name:'A Low-Impact Home', tier:5, req:['insulation','waste-recycling','ethical-consumption'],
    desc:'Cut a household’s energy, water and waste substantially and permanently.' },
]);

addSkills({ cat: 'practical', group: 'Getting Things Done' }, [
  { id:'routine-design', name:'Designing a Routine', tier:3, req:['habits','weekly-review'],
    desc:'Build a week that makes the important things automatic and the rest optional.' },
  { id:'morning-evening', name:'Morning & Evening Routines', tier:2, req:['routine','sleep'],
    desc:'Bookend the day so it starts and ends the same way regardless of what happened.' },
  { id:'checklists', name:'Using Checklists', tier:2, req:['notetaking','time-awareness'],
    desc:'Write down the steps for anything you do rarely and always half-forget.' },
  { id:'sops', name:'Household Standard Procedures', tier:4, req:['checklists','documentation'],
    desc:'Write down how the boiler, the bins and the babysitter work so anyone can do it.' },
  { id:'digital-household', name:'Household Digital Systems', tier:4, req:['note-apps','family-calendar'],
    desc:'Shared lists, documents, passwords and calendars that both adults actually use.' },
  { id:'seasonal-maintenance', name:'A Maintenance Calendar', tier:4, req:['repair','routine-design'],
    desc:'Gutters, boiler, alarms and filters scheduled instead of remembered at failure.' },
]);

addSkills({ cat: 'practical', group: 'More Around the House' }, [
  { id:'furniture-assembly', name:'Flat-Pack & Assembly', tier:2, req:['tool-handling','recipe-reading'],
    desc:'Read the diagram, sort the fittings, and get it square before tightening anything.' },
  { id:'curtains-blinds', name:'Window Dressings', tier:3, req:['wall-fixings','measuring-marking'],
    desc:'Measure, mount and hang so it is level and clears the radiator.' },
  { id:'sealant', name:'Sealing & Caulking', tier:3, req:['adhesives','finishing'],
    desc:'A clean silicone line around a bath that does not go mouldy in six months.' },
  { id:'door-window-repair', name:'Doors, Locks & Windows', tier:3, req:['carpentry-home','home-security'],
    desc:'Ease a sticking door, change a cylinder and fix a failed handle or hinge.' },
  { id:'appliance-repair', name:'Appliance Repair', tier:4, req:['electrical-basics','troubleshooting'],
    desc:'Filters, pumps, belts and seals — the five faults that cover most breakdowns.' },
  { id:'boiler-basics', name:'Boiler & Radiator Basics', tier:3, req:['home-systems','plumbing-basics'],
    desc:'Pressure, bleeding, thermostats and knowing exactly which bit needs a professional.' },
  { id:'garden-maintenance', name:'Keeping a Garden Tidy', tier:2, req:['tool-handling','houseplants'],
    desc:'Mowing, edging, weeding and hedges kept on top of in an hour a week.' },
  { id:'outdoor-diy', name:'Fences, Decks & Paths', tier:4, req:['carpentry-home','structures'],
    desc:'Set posts, lay a base and build outside work that survives ten winters.' },
  { id:'damp-diagnosis', name:'Diagnosing Damp', tier:4, req:['pest-control','insulation'],
    desc:'Tell condensation from penetrating from rising damp before spending anything.' },
]);

addSkills({ cat: 'practical', group: 'Advanced Home' }, [
  { id:'home-energy-retrofit', name:'Retrofitting a Home', tier:5, req:['insulation','renewables','trades-management'],
    desc:'Fabric first, then heating, then generation — in the order that pays back.' },
  { id:'smart-home', name:'Practical Home Automation', tier:4, req:['iot','home-network'],
    desc:'Automate the handful of things that genuinely help and ignore the rest.' },
  { id:'workshop-home', name:'Setting Up a Home Workshop', tier:4, req:['workshop-setup','electrical-basics'],
    desc:'Power, dust, light and storage in a garage, shed or corner of a room.' },
  { id:'self-build', name:'Building Something Habitable', tier:5, req:['renovation','structures','building-regs'],
    desc:'A shed, an extension or a house — planning, trades, inspection and finish.' },
  { id:'off-grid', name:'Off-Grid Systems', tier:5, req:['renewables','water-management','home-energy-retrofit'],
    desc:'Power, water and waste for a building with no mains connection.' },
  { id:'home-accessibility', name:'Adapting a Home', tier:4, req:['older-adult-safety','carpentry-home'],
    desc:'Rails, ramps, thresholds and bathrooms modified for someone who lives there.' },
]);

addSkills({ cat: 'practical', group: 'Living Independently' }, [
  { id:'washing-up', name:'Washing Up & Kitchen Reset', tier:1,
    desc:'Clear as you go and leave the kitchen usable for the next person, including you.' },
  { id:'bed-making', name:'Bedding & Sleep Environment', tier:1,
    desc:'Change, wash and rotate bedding, and set a room up for actual sleep.' },
  { id:'bathroom-upkeep', name:'Bathroom Upkeep', tier:2, req:['cleaning-technique'],
    desc:'Limescale, mould and drains kept on top of weekly rather than annually.' },
  { id:'shopping-trip', name:'Doing a Shop', tier:2, req:['grocery-shopping','errands'],
    desc:'Plan, carry, unpack and put away without half of it going off.' },
  { id:'first-home-setup', name:'Setting Up a First Home', tier:3, req:['renting','utilities-setup','kitchen-kit'],
    desc:'The fifty things you need on day one and the fifty that can wait a year.' },
  { id:'living-alone', name:'Living Alone Well', tier:3, req:['first-home-setup','solitude','cooking-for-one'],
    desc:'Keep standards, structure and company when nobody is there to notice.' },
  { id:'small-space', name:'Living in a Small Space', tier:3, req:['storage-systems','decluttering'],
    desc:'Vertical storage, dual-use furniture and ruthless limits on what comes in.' },
]);
