/* ==================================================================
   Social & Interpersonal — everything that happens between two or
   more people.
================================================================== */

addSkills({ cat: 'social', group: 'Basics' }, [
  { id:'listening', name:'Active Listening', tier:1,
    desc:'Hear the whole point before answering; reflect it back accurately.' },
  { id:'small-talk', name:'Small Talk', tier:1,
    desc:'Open, sustain and gracefully close a low-stakes conversation with a stranger.' },
  { id:'name-memory', name:'Names & Faces', tier:1,
    desc:'Remember who people are and what matters to them.' },
  { id:'politeness', name:'Everyday Courtesy', tier:1,
    desc:'Please, thank you, holding a door, letting someone finish — the cheap stuff that compounds.' },
  { id:'turn-taking', name:'Turn-Taking', tier:2, req:['listening'],
    desc:'Neither dominate nor disappear; notice who has not spoken yet.' },
  { id:'question-asking-social', name:'Asking Good Questions', tier:2, req:['listening','small-talk'],
    desc:'Open questions that make someone want to keep talking about something real.' },
  { id:'reading-the-room', name:'Reading a Room', tier:2, req:['body-language','listening'],
    desc:'Sense mood, hierarchy and tension before you have been told any of it.' },
  { id:'humour', name:'Humour', tier:3, req:['reading-the-room','conversation'],
    desc:'Be funny in a way that includes people rather than at somebody’s expense.' },
]);

addSkills({ cat: 'social', group: 'Conversation' }, [
  { id:'conversation', name:'Conversation Depth', tier:2, req:['small-talk','listening'],
    desc:'Move a conversation from pleasantries to something both people care about.' },
  { id:'self-disclosure', name:'Appropriate Openness', tier:3, req:['conversation','trust-building'],
    desc:'Share enough to be known, at the pace the relationship can actually carry.' },
  { id:'interviewing', name:'Interviewing Someone', tier:3, req:['question-asking-social','listening'],
    desc:'Get a person to tell you what they know, including what they were not going to.' },
  { id:'difficult-conversations', name:'Difficult Conversations', tier:4, req:['empathy','assertive','emotion-regulation'],
    desc:'Open the subject you have been avoiding, and stay in the room while it is hard.' },
  { id:'apologising', name:'Apologising Properly', tier:3, req:['self-honesty','empathy'],
    desc:'Name the harm, take responsibility, change something — no "if you felt".' },
  { id:'receiving-apology', name:'Repairing After a Rupture', tier:4, req:['apologising','forgiveness'],
    desc:'Rebuild a relationship after real damage, or decide honestly that you will not.' },
  { id:'conversational-repair', name:'Recovering an Awkward Moment', tier:3, req:['humour','reading-the-room'],
    desc:'Acknowledge the misfire lightly and get everyone comfortable again.' },
]);

addSkills({ cat: 'social', group: 'Empathy & Support' }, [
  { id:'empathy', name:'Empathy', tier:2, req:['listening'],
    desc:'Model another person’s state accurately enough to respond to what they need.' },
  { id:'comforting', name:'Comforting Someone', tier:3, req:['empathy','sitting-with-feeling'],
    desc:'Be present with someone’s pain without rushing to fix or minimise it.' },
  { id:'trust-building', name:'Building Trust', tier:2, req:['listening','promise-keeping'],
    desc:'Reliability, discretion and consistency — trust is a track record, not a claim.' },
  { id:'perspective-taking', name:'Perspective-Taking', tier:3, req:['empathy','listening'],
    desc:'Genuinely inhabit a viewpoint you find wrong or alien before responding to it.' },
  { id:'generosity', name:'Generosity', tier:2, req:['empathy'],
    desc:'Give time, credit, money and benefit of the doubt without keeping score.' },
  { id:'social-support', name:'Being a Support Network', tier:4, req:['comforting','crisis-support'],
    desc:'Be the person someone calls at 2am, and be actually useful when they do.' },
  { id:'compassion-limits', name:'Compassion Without Burnout', tier:5, req:['social-support','boundaries','stress-management'],
    desc:'Keep caring for years without absorbing everything or shutting down.' },
]);

addSkills({ cat: 'social', group: 'Boundaries & Conflict' }, [
  { id:'assertive', name:'Assertiveness', tier:2, req:['body-language'],
    desc:'State needs, set boundaries and say no without aggression or apology.' },
  { id:'saying-no', name:'Saying No', tier:2, req:['assertive'],
    desc:'Decline clearly, early and without a paragraph of justification.' },
  { id:'boundaries', name:'Setting Boundaries', tier:3, req:['saying-no','self-awareness'],
    desc:'Define what you will and will not do, tell people, and hold it under pressure.' },
  { id:'conflict', name:'Conflict Resolution', tier:3, req:['empathy','assertive'],
    desc:'De-escalate, separate people from problems, find the shared interest underneath.' },
  { id:'de-escalation', name:'De-escalation', tier:3, req:['conflict','emotion-regulation'],
    desc:'Bring the temperature down when someone is shouting, including at you.' },
  { id:'handling-criticism', name:'Taking Criticism', tier:3, req:['emotion-regulation','growth-mindset'],
    desc:'Hear it, extract the true part, and thank them without collapsing or arguing.' },
  { id:'feedback', name:'Giving & Taking Feedback', tier:3, req:['empathy','assertive'],
    desc:'Say the hard, useful thing kindly — and hear it without defending.' },
  { id:'manipulation-defence', name:'Recognising Manipulation', tier:4, req:['boundaries','reading-the-room'],
    desc:'Spot guilt, flattery, moving goalposts and pressure tactics, and name them calmly.' },
  { id:'mediation', name:'Mediating Between Others', tier:5, req:['conflict','facilitation','perspective-taking'],
    desc:'Hold the middle between two parties who both want you to take their side.' },
]);

addSkills({ cat: 'social', group: 'Influence' }, [
  { id:'persuasion', name:'Persuasion', tier:4, req:['perspective-taking','rhetoric'],
    desc:'Move someone toward a view by their reasons, not by yours.' },
  { id:'negotiation', name:'Negotiation', tier:4, req:['conflict','assertive'],
    desc:'Trade across interests to reach a deal both sides will actually honour.' },
  { id:'asking', name:'Asking for What You Want', tier:3, req:['assertive','question-asking-social'],
    desc:'Make a clear, specific, easy-to-say-yes-to request — the most underused skill there is.' },
  { id:'storytelling', name:'Storytelling', tier:4, req:['public-speaking','creative-writing'],
    desc:'Make an idea memorable by giving it characters, stakes and a shape.' },
  { id:'debate', name:'Debating', tier:4, req:['fallacies','public-speaking'],
    desc:'Argue a case under time pressure and rebut what was actually said.' },
  { id:'influence-without-authority', name:'Influence Without Authority', tier:5, req:['persuasion','networking','trust-building'],
    desc:'Get things to happen across an organisation where nobody reports to you.' },
  { id:'advocacy', name:'Persuasive Advocacy', tier:5, req:['storytelling','negotiation','logic'],
    desc:'Change minds and policy at scale with argument, narrative and pressure.' },
]);

addSkills({ cat: 'social', group: 'Speaking to Groups' }, [
  { id:'public-speaking', name:'Public Speaking', tier:3, req:['conversation','body-language'],
    desc:'Hold a room: structure, pace, presence, and recovering when it wobbles.' },
  { id:'impromptu', name:'Speaking Off the Cuff', tier:4, req:['public-speaking','summarising'],
    desc:'Be asked to say something with no warning and say something worth hearing.' },
  { id:'q-and-a', name:'Handling Questions', tier:4, req:['public-speaking','de-escalation'],
    desc:'Take a hostile or confused question and answer the real one underneath it.' },
  { id:'toasts', name:'Toasts & Occasion Speeches', tier:4, req:['public-speaking','storytelling'],
    desc:'Three minutes at a wedding or funeral that land exactly as they should.' },
  { id:'moderating', name:'Moderating a Panel', tier:4, req:['interviewing','facilitation'],
    desc:'Keep it moving, keep it fair, and make the panellists look good.' },
  { id:'facilitation', name:'Facilitation', tier:4, req:['public-speaking','conflict'],
    desc:'Run a group so it reaches a real decision and everyone is heard.' },
  { id:'workshop-running', name:'Running a Workshop', tier:5, req:['facilitation','lesson-planning'],
    desc:'Design and run a day where a group produces something, not just discusses it.' },
]);

addSkills({ cat: 'social', group: 'Networks & Groups' }, [
  { id:'networking', name:'Networking', tier:3, req:['conversation','name-memory'],
    desc:'Build and maintain a wide, genuine web of professional relationships.' },
  { id:'keeping-in-touch', name:'Keeping in Touch', tier:2, req:['name-memory','time-management'],
    desc:'Sustain friendships across distance and years through deliberate small contact.' },
  { id:'introducing-people', name:'Connecting People', tier:3, req:['networking','empathy'],
    desc:'Make an introduction both sides are glad to have received.' },
  { id:'hosting', name:'Hosting', tier:3, req:['reading-the-room','cooking-basics'],
    desc:'Run a gathering where people meet each other and nobody is stranded.' },
  { id:'group-dynamics', name:'Group Dynamics', tier:4, req:['reading-the-room','systems-thinking'],
    desc:'See the roles, coalitions and unspoken rules operating in any standing group.' },
  { id:'mentoring', name:'Mentoring & Coaching', tier:4, req:['feedback','empathy'],
    desc:'Grow someone else’s capability deliberately over months, not minutes.' },
  { id:'leadership', name:'Leadership', tier:5, req:['mentoring','negotiation','facilitation'],
    desc:'Set direction, earn trust, and get a group to do hard things together.' },
  { id:'community', name:'Community Building', tier:5, req:['networking','facilitation'],
    desc:'Create a group with its own norms, momentum and life beyond you.' },
  { id:'coalition-building', name:'Building Coalitions', tier:5, req:['influence-without-authority','community'],
    desc:'Assemble people with different interests behind one outcome and keep them there.' },
]);

addSkills({ cat: 'social', group: 'Across Cultures' }, [
  { id:'cultural-awareness', name:'Cultural Awareness', tier:3, req:['perspective-taking','geography-literacy'],
    desc:'Notice that your normal is local, and find out what theirs is before assuming.' },
  { id:'cross-cultural', name:'Cross-Cultural Communication', tier:4, req:['cultural-awareness','listening'],
    desc:'Directness, hierarchy, time and face vary; adjust without caricaturing.' },
  { id:'inclusion', name:'Inclusive Practice', tier:4, req:['cultural-awareness','empathy'],
    desc:'Build rooms, documents and processes that work for people unlike you.' },
  { id:'allyship', name:'Speaking Up for Others', tier:4, req:['inclusion','courage'],
    desc:'Interrupt the comment, back the person, and take some of the cost yourself.' },
  { id:'intercultural-leadership', name:'Leading Across Cultures', tier:5, req:['cross-cultural','leadership','inclusion'],
    desc:'Run a team spread across countries, languages and expectations of authority.' },
]);

addSkills({ cat: 'social', group: 'Reading People' }, [
  { id:'microexpression', name:'Reading Faces', tier:3, req:['body-language','empathy'],
    desc:'Notice the flicker of discomfort or disagreement someone did not mean to show.' },
  { id:'tone-reading', name:'Hearing Tone', tier:2, req:['listening'],
    desc:'Register what the voice is doing when the words say something else.' },
  { id:'lie-scepticism', name:'Assessing Honesty', tier:4, req:['tone-reading','bias-awareness'],
    desc:'Check claims against evidence, and distrust your own confidence in reading liars.' },
  { id:'motive-reading', name:'Understanding Motives', tier:4, req:['perspective-taking','group-dynamics'],
    desc:'Work out what someone is actually optimising for, which is rarely what they said.' },
  { id:'personality-literacy', name:'Personality Differences', tier:3, req:['empathy','statistics'],
    desc:'Real, measurable variation in temperament — used with scepticism about typologies.' },
  { id:'neurodiversity', name:'Neurodiversity Awareness', tier:3, req:['empathy','perspective-taking'],
    desc:'Different processing, sensory needs and communication styles taken as fact, not failure.' },
]);

addSkills({ cat: 'social', group: 'Everyday Situations' }, [
  { id:'introductions', name:'Introducing Yourself', tier:1,
    desc:'A short, warm, memorable account of who you are that changes with the room.' },
  { id:'phone-calls', name:'Making Phone Calls', tier:2, req:['articulation','assertive'],
    desc:'Call the surgery, the bank or the stranger without rehearsing for an hour.' },
  { id:'queue-etiquette', name:'Public Behaviour', tier:1,
    desc:'Queues, volume, space and the small courtesies of shared public places.' },
  { id:'complaining-in-person', name:'Complaining in Person', tier:3, req:['assertive','de-escalation'],
    desc:'Be firm with a person who is not at fault and still get the problem solved.' },
  { id:'condolences', name:'Saying the Right Thing After a Loss', tier:3, req:['comforting','grief'],
    desc:'Show up, say something short and true, and offer something specific.' },
  { id:'celebrating-others', name:'Celebrating Other People', tier:2, req:['generosity','empathy'],
    desc:'Notice, mark and be genuinely glad about someone else’s good news.' },
  { id:'small-favours', name:'Asking and Doing Favours', tier:3, req:['asking','generosity'],
    desc:'Ask for help easily, give it readily, and keep no ledger either way.' },
  { id:'awkward-topics', name:'Raising an Awkward Subject', tier:4, req:['difficult-conversations','humour'],
    desc:'Money, smell, breath, behaviour — say it once, kindly, and move on.' },
]);

addSkills({ cat: 'social', group: 'Written & Remote' }, [
  { id:'letter-writing', name:'Letter Writing', tier:3, req:['sentence-craft','empathy'],
    desc:'A real letter for thanks, condolence or congratulation, in your own hand.' },
  { id:'async-communication', name:'Communicating Asynchronously', tier:4, req:['email-professional','summarising'],
    desc:'Write so nobody needs a follow-up call to understand what you meant.' },
  { id:'video-call-presence', name:'Video Calls', tier:4, req:['camera-presence','turn-taking'],
    desc:'Read a grid of faces, manage turn-taking, and keep energy up through a screen.' },
  { id:'long-distance-relationships', name:'Relationships at a Distance', tier:4, req:['keeping-in-touch','async-communication'],
    desc:'Deliberate rhythm and real conversation across timezones and years.' },
]);

addSkills({ cat: 'social', group: 'Everyday Kindness' }, [
  { id:'helping-strangers', name:'Helping a Stranger', tier:1,
    desc:'Notice someone struggling and offer something specific rather than looking away.' },
  { id:'giving-directions', name:'Giving Directions & Explanations', tier:2, req:['articulation','wayfinding'],
    desc:'Landmarks, left and right, and checking they actually got it.' },
  { id:'patience-with-people', name:'Patience With People', tier:2, req:['emotion-regulation','politeness'],
    desc:'Stay pleasant with someone slow, confused or having a much worse day than you.' },
  { id:'including-people', name:'Including People', tier:2, req:['reading-the-room','generosity'],
    desc:'Notice who is on the edge of the group and bring them in.' },
  { id:'discretion', name:'Discretion', tier:3, req:['trust-building','boundaries'],
    desc:'Hold what you were told in confidence, permanently, including from your partner.' },
  { id:'not-gossiping', name:'Refusing Gossip', tier:3, req:['discretion','courage'],
    desc:'Decline to join in, and change the subject without making a speech about it.' },
  { id:'praise', name:'Praising Well', tier:3, req:['feedback','celebrating-others'],
    desc:'Specific, timely, about the work — praise that means something.' },
  { id:'discomfort-tolerance-social', name:'Sitting With Social Discomfort', tier:3, req:['sitting-with-feeling','small-talk'],
    desc:'Let a silence, a rejection or an awkward pause happen without filling it.' },
]);

addSkills({ cat: 'social', group: 'Groups You Are In' }, [
  { id:'joining-a-group', name:'Joining a Group', tier:2, req:['small-talk','introductions'],
    desc:'Walk into a room where everyone knows each other and come back next week.' },
  { id:'club-participation', name:'Being a Good Member', tier:3, req:['joining-a-group','volunteering'],
    desc:'Take a turn on the rota, pay your subs and do the job nobody wants once a year.' },
  { id:'team-membership', name:'Being a Good Teammate', tier:3, req:['collaboration','good-sport'],
    desc:'Cover for people, share credit, and raise problems inside the team first.' },
  { id:'group-decisions', name:'Deciding as a Group', tier:4, req:['facilitation','turn-taking'],
    desc:'Consensus, voting and knowing which one this decision deserves.' },
  { id:'leaving-a-group', name:'Leaving Well', tier:4, req:['club-participation','handover'],
    desc:'Give notice, hand over what you were holding, and go without a scene.' },
  { id:'succession-social', name:'Handing on a Role', tier:5, req:['leaving-a-group','mentoring','institution-building'],
    desc:'Find and train your replacement so the thing survives your leaving.' },
]);
