/* ==================================================================
   Style & Self-Presentation — grooming, clothes, and the signals you
   send before you have said anything.
================================================================== */

addSkills({ cat: 'style', group: 'Grooming' }, [
  { id:'grooming-basics', name:'Grooming Basics', tier:1,
    desc:'Clean, trimmed and presentable every day without thinking about it.' },
  { id:'hair-care', name:'Hair Care', tier:1,
    desc:'Wash, condition and manage your own hair type rather than fighting it.' },
  { id:'shaving', name:'Shaving & Beard Care', tier:2, req:['grooming-basics'],
    desc:'A close shave or a maintained beard, without irritation or ingrown hairs.' },
  { id:'haircut-brief', name:'Briefing a Barber', tier:2, req:['hair-care'],
    desc:'Describe the cut you want in terms a stylist can actually act on.' },
  { id:'home-haircut', name:'Cutting Hair', tier:3, req:['haircut-brief','fine-motor'],
    desc:'Clipper grades, blending and a straight line — cutting hair without regret.' },
  { id:'nail-care', name:'Nail & Hand Care', tier:2, req:['grooming-basics'],
    desc:'Shape, cuticles and clean hands — the detail people notice unconsciously.' },
  { id:'skincare-routine', name:'A Skincare Routine', tier:3, req:['skin-care','grooming-basics'],
    desc:'A short evidence-based routine matched to your skin, kept up for months.' },
  { id:'fragrance', name:'Fragrance', tier:3, req:['grooming-basics'],
    desc:'Notes, longevity and restraint — choosing and wearing scent well.' },
  { id:'makeup-basics', name:'Makeup Basics', tier:2, req:['grooming-basics'],
    desc:'Base, brows and a clean everyday face in under ten minutes.' },
  { id:'makeup-advanced', name:'Advanced Makeup', tier:4, req:['makeup-basics','colour-theory'],
    desc:'Sculpting, colour matching and looks that hold up under camera or stage light.' },
]);

addSkills({ cat: 'style', group: 'Clothing' }, [
  { id:'dressing-appropriately', name:'Dressing for the Occasion', tier:1,
    desc:'Read a dress code and land inside it without over- or under-shooting.' },
  { id:'garment-care', name:'Garment Care', tier:2, req:['laundry'],
    desc:'Fabrics, symbols, ironing, steaming and storage that make clothes last years.' },
  { id:'fit', name:'Understanding Fit', tier:2, req:['dressing-appropriately'],
    desc:'Shoulders, sleeve, rise and break — why a cheap thing that fits beats an expensive one that does not.' },
  { id:'wardrobe-building', name:'Building a Wardrobe', tier:3, req:['fit','budgeting'],
    desc:'A small set of pieces that combine, suit you, and cover your actual life.' },
  { id:'colour-for-you', name:'Colour & Pattern for You', tier:3, req:['fit','colour-theory'],
    desc:'Which palettes and patterns work with your colouring and against each other.' },
  { id:'formalwear', name:'Formalwear', tier:4, req:['wardrobe-building','fit'],
    desc:'Suits, black tie and traditional dress — the rules and when they can bend.' },
  { id:'tailoring-brief', name:'Working With a Tailor', tier:3, req:['fit'],
    desc:'Know which alterations are cheap, which are impossible, and how to ask.' },
  { id:'shoe-care', name:'Shoe Care', tier:2, req:['garment-care'],
    desc:'Clean, condition, polish and resole — shoes as a ten-year purchase.' },
  { id:'accessorising', name:'Accessories', tier:3, req:['wardrobe-building'],
    desc:'Watch, belt, bag, jewellery — additions that finish an outfit instead of shouting.' },
  { id:'personal-style', name:'A Personal Style', tier:5, req:['wardrobe-building','colour-for-you','self-concept'],
    desc:'A recognisable, consistent way of dressing that is unmistakably yours.' },
  { id:'sustainable-fashion', name:'Buying Clothes Well', tier:4, req:['wardrobe-building','ethical-consumption'],
    desc:'Quality signals, second-hand, repair and buying a third as much for twice as long.' },
]);

addSkills({ cat: 'style', group: 'Presence' }, [
  { id:'body-language', name:'Body Language & Eye Contact', tier:1,
    desc:'Read and project openness, attention and confidence without speaking.' },
  { id:'handshake-greeting', name:'Greetings & First Impressions', tier:1,
    desc:'Arrive, greet and introduce yourself so the first ten seconds go well.' },
  { id:'voice-presence', name:'Voice & Diction', tier:3, req:['body-language','voice-care'],
    desc:'Pitch, pace, volume and articulation that make you easy and pleasant to listen to.' },
  { id:'table-manners', name:'Table Manners', tier:2, req:['handshake-greeting'],
    desc:'Cutlery, pace, toasts and hosting conventions across a few cultures.' },
  { id:'etiquette', name:'Etiquette', tier:3, req:['table-manners','cultural-awareness'],
    desc:'Invitations, gifts, thank-yous and the small formalities that smooth relationships.' },
  { id:'stage-presence', name:'Stage Presence', tier:4, req:['voice-presence','public-speaking'],
    desc:'Occupy a stage, hold stillness, and make an audience want to keep watching.' },
  { id:'camera-presence', name:'On Camera', tier:4, req:['voice-presence','composition'],
    desc:'Framing, eyeline, lighting and energy for video calls, interviews and recordings.' },
  { id:'photogenic', name:'Being Photographed', tier:3, req:['body-language','composition'],
    desc:'Angles, posture and expression that produce photos you actually like.' },
  { id:'personal-brand', name:'Professional Presence', tier:5, req:['personal-style','camera-presence','networking'],
    desc:'A coherent public self across a room, a profile and a stage that matches the real one.' },
]);

addSkills({ cat: 'style', group: 'Bodies & Appearance' }, [
  { id:'body-acceptance', name:'Body Acceptance', tier:4, req:['self-concept','body-weight-awareness'],
    desc:'Treat your body as something to look after rather than something to fix.' },
  { id:'dressing-your-shape', name:'Dressing Your Body', tier:4, req:['fit','body-acceptance'],
    desc:'Proportion and line that work with the body you have today.' },
  { id:'ageing-well', name:'Ageing Visibly', tier:5, req:['personal-style','body-acceptance','equanimity'],
    desc:'Adapt grooming and dress as you change, without either denial or surrender.' },
  { id:'style-for-context', name:'Reading Dress Codes Abroad', tier:4, req:['dressing-appropriately','cultural-awareness'],
    desc:'Modesty, formality and colour norms that differ sharply from your own.' },
  { id:'uniform-thinking', name:'A Personal Uniform', tier:4, req:['wardrobe-building','decision-fatigue'],
    desc:'Decide once, wear it repeatedly, and get the mornings back.' },
  { id:'photo-curation', name:'Curating How You Appear', tier:4, req:['photogenic','digital-footprint'],
    desc:'Choose the images of you that exist publicly, deliberately.' },
]);

addSkills({ cat: 'style', group: 'Everyday Presentation' }, [
  { id:'clean-clothes', name:'Turning Up Clean & Pressed', tier:1,
    desc:'The baseline that people notice only in its absence.' },
  { id:'posture-presence', name:'Standing Like You Mean It', tier:2, req:['posture','body-language'],
    desc:'Open chest, relaxed shoulders, feet planted — half of confidence is mechanical.' },
  { id:'smiling', name:'Warmth', tier:1,
    desc:'A genuine greeting and an open face — the cheapest social advantage there is.' },
  { id:'listening-face', name:'Looking Like You Are Listening', tier:2, req:['listening','body-language'],
    desc:'Eyes, nods and stillness that tell someone they have your attention.' },
  { id:'occasion-prep', name:'Preparing for an Occasion', tier:3, req:['dressing-appropriately','garment-care'],
    desc:'Clothes checked, shoes done and everything laid out the night before.' },
]);

addSkills({ cat: 'style', group: 'Looking After What You Wear' }, [
  { id:'shoe-fitting', name:'Buying Shoes That Fit', tier:2, req:['fit','foot-care'],
    desc:'Size varies by maker; measure, try both feet, and walk before buying.' },
  { id:'fabric-knowledge', name:'Knowing Fabrics', tier:3, req:['garment-care','observation'],
    desc:'Wool, cotton, linen and synthetics — how each wears, breathes and lasts.' },
  { id:'wardrobe-audit', name:'Auditing a Wardrobe', tier:3, req:['decluttering','fit'],
    desc:'Find what you actually wear, why the rest sits there, and act on both.' },
  { id:'capsule-packing', name:'Packing a Capsule', tier:4, req:['wardrobe-building','packing'],
    desc:'Ten pieces that combine into two weeks of appropriate outfits.' },
  { id:'jewellery-watches', name:'Jewellery & Watches', tier:4, req:['accessorising','collecting'],
    desc:'Quality, proportion and provenance in the things you wear every day for decades.' },
  { id:'glasses-choice', name:'Choosing Glasses', tier:3, req:['eye-care','colour-for-you'],
    desc:'Frame shape, size and material for a thing that sits on your face all day.' },
  { id:'sustainable-wardrobe-care', name:'Making Clothes Last', tier:4, req:['clothing-repair','fabric-knowledge'],
    desc:'Wash less, store better, repair early — the cheapest sustainability there is.' },
  { id:'style-for-work', name:'Dressing for Your Field', tier:3, req:['dressing-appropriately','workplace-norms'],
    desc:'Read what your industry signals and decide deliberately where you sit in it.' },
]);
