/* ==================================================================
   Technical & Digital — operating computers, building with them, and
   not being operated on by them.
================================================================== */

addSkills({ cat: 'tech', group: 'Digital Basics' }, [
  { id:'typing', name:'Touch Typing', tier:1,
    desc:'Type without looking, fast enough that the keyboard stops being the bottleneck.' },
  { id:'computer-literacy', name:'Computer Literacy', tier:1,
    desc:'Files, apps, settings, backups — operating a computer with intent.' },
  { id:'phone-literacy', name:'Smartphone Competence', tier:1,
    desc:'Settings, permissions, storage and updates — owning the device rather than renting it.' },
  { id:'web-search', name:'Search & Research Online', tier:1,
    desc:'Query precisely and find the actual answer rather than the first result.' },
  { id:'digital-safety', name:'Digital Safety', tier:1,
    desc:'Passwords, 2FA, phishing, privacy settings, and what not to post.' },
  { id:'keyboard-shortcuts', name:'Keyboard Shortcuts', tier:2, req:['typing','computer-literacy'],
    desc:'Drive your daily software without the mouse; minutes a day compound into weeks.' },
  { id:'file-org', name:'File & System Organisation', tier:2, req:['computer-literacy'],
    desc:'Naming, structure, sync and backup you can still navigate in a year.' },
  { id:'backup-strategy', name:'Backups That Work', tier:3, req:['file-org','digital-safety'],
    desc:'Three copies, two media, one offsite — and a restore you have actually tested.' },
  { id:'troubleshooting', name:'Troubleshooting', tier:2, req:['computer-literacy'],
    desc:'Isolate a fault by bisecting: what changed, what else breaks, what fixes it.' },
  { id:'device-maintenance', name:'Device Maintenance', tier:2, req:['computer-literacy'],
    desc:'Storage, updates, batteries, thermals — keeping hardware useful for six years.' },
  { id:'accessibility-tools', name:'Accessibility Tools', tier:2, req:['computer-literacy'],
    desc:'Screen readers, magnification, captions and dictation, for yourself or others.' },
]);

addSkills({ cat: 'tech', group: 'Living Online' }, [
  { id:'email-competence', name:'Email Competence', tier:1,
    desc:'Write, thread, filter and archive so your inbox is not a source of dread.' },
  { id:'info-filtering', name:'Information Filtering', tier:2, req:['web-search','digital-safety'],
    desc:'Judge sources, spot manipulation, and manage your own information diet.' },
  { id:'online-etiquette', name:'Online Communication Norms', tier:3, req:['email-competence','register'],
    desc:'Tone, threading and escalation across chat, email, forums and comments.' },
  { id:'privacy-management', name:'Privacy Management', tier:3, req:['digital-safety','info-filtering'],
    desc:'Control your data footprint: trackers, permissions, deletion requests, aliases.' },
  { id:'misinformation', name:'Spotting Misinformation', tier:3, req:['info-filtering','critical-reading'],
    desc:'Reverse image search, source tracing, and recognising engineered outrage.' },
  { id:'deepfake-literacy', name:'Synthetic Media Literacy', tier:4, req:['misinformation','ai-literacy'],
    desc:'Assume audio and video can be faked, and know what verification is left.' },
  { id:'digital-minimalism', name:'Digital Minimalism', tier:3, req:['attention-hygiene','privacy-management'],
    desc:'Decide what technology earns a place in your life and remove the rest.' },
  { id:'online-community', name:'Participating Online Well', tier:3, req:['online-etiquette','conflict'],
    desc:'Contribute to forums and chats in ways that raise rather than lower the tone.' },
  { id:'digital-footprint', name:'Managing Your Public Record', tier:4, req:['privacy-management','portfolio'],
    desc:'Audit what is findable about you and shape what a stranger sees first.' },
  { id:'remote-collaboration', name:'Remote Collaboration Tools', tier:3, req:['online-etiquette','file-org'],
    desc:'Shared docs, tickets, video and async writing used well rather than constantly.' },
]);

addSkills({ cat: 'tech', group: 'Everyday Tools' }, [
  { id:'word-processing', name:'Document Production', tier:2, req:['computer-literacy','typing'],
    desc:'Styles, templates, track changes and exports that survive someone else opening them.' },
  { id:'spreadsheets', name:'Spreadsheets', tier:2, req:['computer-literacy','numeracy'],
    desc:'Formulas, lookups and pivots — the most useful tool most people never learn.' },
  { id:'spreadsheet-modelling', name:'Spreadsheet Modelling', tier:3, req:['spreadsheets','estimation'],
    desc:'Build a forecast or budget model with assumptions separated from calculations.' },
  { id:'presentations', name:'Building Slides', tier:3, req:['word-processing','design'],
    desc:'One idea per slide, readable from the back, supporting you rather than replacing you.' },
  { id:'note-apps', name:'Notes & Task Tools', tier:2, req:['file-org','time-management'],
    desc:'A capture-and-review system you trust enough to stop holding things in your head.' },
  { id:'personal-automation', name:'No-Code Automation', tier:3, req:['note-apps','troubleshooting'],
    desc:'Wire your own tools together with shortcuts, rules and integrations.' },
  { id:'ai-literacy', name:'AI Tool Literacy', tier:2, req:['web-search','info-filtering'],
    desc:'What language models do well, where they confabulate, and how to check them.' },
  { id:'prompting', name:'Effective Prompting', tier:3, req:['ai-literacy','sentence-craft'],
    desc:'Give a model the context, constraints and examples that make its output usable.' },
  { id:'ai-workflow', name:'Building AI Into Your Work', tier:4, req:['prompting','personal-automation'],
    desc:'Delegate real tasks to models with verification steps you actually run.' },
]);

addSkills({ cat: 'tech', group: 'Programming' }, [
  { id:'programming-basics', name:'Programming Basics', tier:2, req:['typing','computer-literacy'],
    desc:'Variables, loops, functions, debugging — one language, properly.' },
  { id:'data-structures', name:'Data Structures', tier:3, req:['programming-basics','discrete-maths'],
    desc:'Arrays, maps, trees and graphs, and knowing which one this problem wants.' },
  { id:'algorithms', name:'Algorithms & Complexity', tier:4, req:['data-structures','proof'],
    desc:'Sorting, searching, dynamic programming, and reasoning about cost before running it.' },
  { id:'debugging', name:'Debugging', tier:3, req:['programming-basics','troubleshooting'],
    desc:'Form a hypothesis, bisect, read the stack trace, and stop guessing.' },
  { id:'testing', name:'Automated Testing', tier:3, req:['programming-basics','debugging'],
    desc:'Unit, integration and regression tests that let you change code without fear.' },
  { id:'version-control', name:'Version Control', tier:3, req:['programming-basics','file-org'],
    desc:'Git: branches, merges, history and collaborating without losing work.' },
  { id:'cli', name:'Command Line', tier:3, req:['file-org','programming-basics'],
    desc:'Shell navigation, pipes and tooling — the terminal as a power multiplier.' },
  { id:'scripting', name:'Automation & Scripting', tier:3, req:['cli'],
    desc:'Automate the repetitive parts of your own work and never do them again.' },
  { id:'regex', name:'Regular Expressions', tier:3, req:['scripting'],
    desc:'Match, extract and rewrite text patterns without writing a parser.' },
  { id:'code-reading', name:'Reading Other People’s Code', tier:4, req:['version-control','debugging'],
    desc:'Get productive in an unfamiliar hundred-thousand-line codebase in a week.' },
  { id:'refactoring', name:'Refactoring', tier:4, req:['testing','code-reading'],
    desc:'Change structure without changing behaviour, in safe reversible steps.' },
  { id:'code-review', name:'Code Review', tier:4, req:['code-reading','feedback'],
    desc:'Catch the real problems, ignore the trivia, and leave the author better.' },
  { id:'functional-programming', name:'Functional Programming', tier:4, req:['algorithms','refactoring'],
    desc:'Immutability, composition and types as a way of making illegal states impossible.' },
  { id:'concurrency', name:'Concurrency', tier:5, req:['algorithms','architecture'],
    desc:'Threads, async and locks — and the race conditions that only appear in production.' },
  { id:'systems-programming', name:'Systems Programming', tier:5, req:['concurrency','computer-architecture'],
    desc:'Memory, pointers and the operating system boundary, in C or Rust.' },
]);

addSkills({ cat: 'tech', group: 'Building Software' }, [
  { id:'html-css', name:'HTML & CSS', tier:2, req:['computer-literacy','typing'],
    desc:'Structure and style a page that works on a phone and a screen reader.' },
  { id:'web-dev', name:'Web Development', tier:3, req:['programming-basics','design'],
    desc:'Build and ship a working web application front to back.' },
  { id:'apis', name:'Working With APIs', tier:3, req:['programming-basics','web-dev'],
    desc:'Read docs, authenticate, handle errors and rate limits, and integrate a service.' },
  { id:'frontend', name:'Frontend Engineering', tier:4, req:['web-dev','html-css','testing'],
    desc:'State, components, performance and accessibility in a real interface.' },
  { id:'backend', name:'Backend Engineering', tier:4, req:['apis','databases'],
    desc:'Services, auth, queues and the failure modes that only show up under load.' },
  { id:'mobile-dev', name:'Mobile Development', tier:4, req:['web-dev','ux-design'],
    desc:'Build, sign and ship an app through a store review process.' },
  { id:'game-dev', name:'Game Development', tier:4, req:['programming-basics','game-design','linear-algebra'],
    desc:'Loop, physics, assets and input — making something playable and shipping it.' },
  { id:'architecture', name:'Software Architecture', tier:4, req:['web-dev','version-control'],
    desc:'Design systems that stay changeable as they grow; trade-offs over dogma.' },
  { id:'api-design', name:'API Design', tier:5, req:['architecture','technical-writing'],
    desc:'Interfaces other developers can use correctly on the first try, and version safely.' },
  { id:'performance-engineering', name:'Performance Engineering', tier:5, req:['algorithms','architecture','observability'],
    desc:'Measure first, then fix the thing that is actually slow.' },
]);

addSkills({ cat: 'tech', group: 'Data' }, [
  { id:'data-cleaning', name:'Data Cleaning', tier:3, req:['spreadsheets','scripting'],
    desc:'Types, nulls, duplicates and encoding — the eighty percent of any data job.' },
  { id:'data-analysis', name:'Data Analysis', tier:3, req:['spreadsheets','statistics'],
    desc:'Clean, explore and visualise a real dataset to answer a real question.' },
  { id:'databases', name:'Databases & SQL', tier:4, req:['data-analysis','programming-basics'],
    desc:'Model data, write real queries, and understand indexes and transactions.' },
  { id:'data-viz', name:'Data Visualisation', tier:4, req:['data-analysis','design'],
    desc:'Charts that make the finding obvious and do not mislead by accident.' },
  { id:'data-pipelines', name:'Data Pipelines', tier:5, req:['databases','scripting','architecture'],
    desc:'Scheduled, monitored, idempotent flows that people can depend on at 6am.' },
  { id:'data-governance', name:'Data Governance & Privacy', tier:5, req:['databases','privacy-management','compliance'],
    desc:'Retention, minimisation, access control and knowing what you are allowed to keep.' },
  { id:'experimentation', name:'A/B Testing & Experimentation', tier:5, req:['data-analysis','research-design'],
    desc:'Design an online experiment that will not fool you with a false positive.' },
]);

addSkills({ cat: 'tech', group: 'AI & Machine Learning' }, [
  { id:'ml', name:'Machine Learning', tier:4, req:['data-analysis','calculus'],
    desc:'Train, evaluate and deploy models — and know when not to use one.' },
  { id:'ml-evaluation', name:'Model Evaluation', tier:5, req:['ml','experimentation'],
    desc:'Baselines, leakage, drift and metrics that reflect what you actually care about.' },
  { id:'deep-learning', name:'Deep Learning', tier:5, req:['ml','linear-algebra'],
    desc:'Architectures, training dynamics and the practicalities of GPUs and data.' },
  { id:'ai-systems', name:'AI Systems Building', tier:5, req:['ml','architecture'],
    desc:'Build products on models: evaluation, pipelines, cost, safety and iteration.' },
  { id:'ai-ethics', name:'AI Ethics & Impact', tier:5, req:['ml-evaluation','ethical-framework'],
    desc:'Bias, consent, labour and downstream harm as engineering constraints, not footnotes.' },
]);

addSkills({ cat: 'tech', group: 'Infrastructure' }, [
  { id:'networking-basics', name:'How Networks Work', tier:3, req:['computer-literacy','troubleshooting'],
    desc:'IP, DNS, HTTP and why the wifi is fine but the site is not.' },
  { id:'home-network', name:'Home Networking', tier:3, req:['networking-basics'],
    desc:'Router, wifi channels, port forwarding, VPN and a guest network that is separate.' },
  { id:'linux-admin', name:'Linux Administration', tier:4, req:['cli','networking-basics'],
    desc:'Users, permissions, services, logs and packages on a machine you actually own.' },
  { id:'containers', name:'Containers', tier:4, req:['linux-admin','version-control'],
    desc:'Build reproducible images and run them the same way everywhere.' },
  { id:'cloud', name:'Cloud Infrastructure', tier:4, req:['linux-admin','networking-basics'],
    desc:'Compute, storage, networking and a bill you understand before it arrives.' },
  { id:'iac', name:'Infrastructure as Code', tier:5, req:['cloud','version-control'],
    desc:'Declare infrastructure in a repo so it can be reviewed, rebuilt and rolled back.' },
  { id:'cicd', name:'CI/CD', tier:5, req:['testing','containers'],
    desc:'Automated build, test and deploy that makes releasing boring.' },
  { id:'observability', name:'Observability', tier:5, req:['cloud','data-analysis'],
    desc:'Logs, metrics and traces that let you answer a question you did not anticipate.' },
  { id:'oncall', name:'On-Call & Incident Response', tier:5, req:['observability','emotion-regulation'],
    desc:'Triage, mitigate, communicate and write the blameless post-mortem afterwards.' },
  { id:'systems-engineering', name:'Systems Engineering', tier:5, req:['architecture','databases','cybersecurity'],
    desc:'Run large, reliable, observable systems in production under real load.' },
]);

addSkills({ cat: 'tech', group: 'Security' }, [
  { id:'password-hygiene', name:'Password & Account Hygiene', tier:1,
    desc:'A manager, unique passwords, hardware keys, and recovery codes stored offline.' },
  { id:'threat-modelling', name:'Threat Modelling', tier:3, req:['digital-safety','risk-assessment'],
    desc:'Ask who would attack this, why, and what they would actually get.' },
  { id:'encryption-literacy', name:'Encryption Literacy', tier:3, req:['digital-safety','networking-basics'],
    desc:'Transport vs. at rest, end-to-end, keys and signatures — what protects what.' },
  { id:'cybersecurity', name:'Cybersecurity', tier:4, req:['cli','digital-safety','scripting'],
    desc:'Threat models, hardening and incident response for systems you own.' },
  { id:'secure-coding', name:'Secure Coding', tier:5, req:['cybersecurity','code-review'],
    desc:'Injection, authz, secrets and dependencies — writing code that resists attack.' },
  { id:'opsec', name:'Operational Security', tier:4, req:['threat-modelling','privacy-management'],
    desc:'Compartmentalisation and habits for a genuinely elevated risk profile.' },
  { id:'digital-forensics', name:'Digital Forensics', tier:5, req:['cybersecurity','linux-admin'],
    desc:'Preserve evidence and reconstruct what happened after a compromise.' },
]);

addSkills({ cat: 'tech', group: 'Hardware & Making' }, [
  { id:'pc-building', name:'Building a Computer', tier:3, req:['device-maintenance','troubleshooting'],
    desc:'Choose parts that fit together and assemble a machine that posts first time.' },
  { id:'computer-architecture', name:'How Computers Work', tier:4, req:['programming-basics','electronics'],
    desc:'Registers, memory hierarchy, instruction sets — from transistor to program.' },
  { id:'microcontrollers', name:'Microcontrollers', tier:3, req:['programming-basics','electronics'],
    desc:'Arduino or Pi: read a sensor, drive an output, and debug without a screen.' },
  { id:'iot', name:'Home Automation', tier:4, req:['microcontrollers','home-network'],
    desc:'Sensors, hubs and rules that make a house respond, without cloud lock-in.' },
  { id:'threed-printing', name:'3D Printing', tier:3, req:['cad','troubleshooting'],
    desc:'Slice, level, tune and actually get a functional part off the bed.' },
  { id:'repair-electronics', name:'Electronics Repair', tier:4, req:['electronics','soldering'],
    desc:'Diagnose to component level and fix what everyone else would replace.' },
  { id:'oss-leadership', name:'Open Source Leadership', tier:5, req:['architecture','community'],
    desc:'Maintain a project other people depend on — code, review and governance.' },
]);

addSkills({ cat: 'tech', group: 'IT & Support' }, [
  { id:'os-literacy', name:'Multiple Operating Systems', tier:2, req:['computer-literacy'],
    desc:'Move between Windows, macOS and Linux without losing your footing.' },
  { id:'help-desk', name:'Helping Others With Tech', tier:2, req:['troubleshooting','empathy'],
    desc:'Diagnose over the phone, without condescension, from a vague description.' },
  { id:'data-recovery', name:'Data Recovery', tier:4, req:['backup-strategy','linux-admin'],
    desc:'Get files off a dying drive without making it worse on the first attempt.' },
  { id:'device-migration', name:'Migrating to a New Device', tier:3, req:['backup-strategy','file-org'],
    desc:'Move everything, verify it, and wipe the old one properly before it leaves.' },
  { id:'printer-peripherals', name:'Peripherals & Printing', tier:2, req:['troubleshooting'],
    desc:'Drivers, queues and connections — the eternally unreasonable part of computing.' },
  { id:'software-licensing', name:'Software Licensing', tier:3, req:['contracts-reading','computer-literacy'],
    desc:'Open source licences, subscriptions and what you are actually allowed to do.' },
]);

addSkills({ cat: 'tech', group: 'More Programming' }, [
  { id:'python', name:'Python', tier:3, req:['programming-basics'],
    desc:'The general-purpose language most likely to be the right first answer.' },
  { id:'javascript', name:'JavaScript', tier:3, req:['programming-basics','html-css'],
    desc:'The language of the browser, its runtime model, and its many sharp edges.' },
  { id:'typed-languages', name:'Statically Typed Languages', tier:4, req:['data-structures','testing'],
    desc:'Use a type system as a design tool rather than an obstacle.' },
  { id:'sql-fluency', name:'SQL Fluency', tier:4, req:['databases'],
    desc:'Joins, window functions and CTEs written directly rather than through a tool.' },
  { id:'shell-scripting', name:'Shell Scripting', tier:4, req:['scripting','regex'],
    desc:'Robust bash with error handling, quoting and things that survive a space in a filename.' },
  { id:'dependency-management', name:'Dependency Management', tier:4, req:['version-control','cybersecurity'],
    desc:'Pinning, updating and auditing the hundreds of things your project trusts.' },
  { id:'build-systems', name:'Build Systems', tier:4, req:['cli','version-control'],
    desc:'Reproducible builds, caching and the difference between it works here and it works.' },
  { id:'debugging-production', name:'Debugging in Production', tier:5, req:['observability','debugging'],
    desc:'Diagnose a fault you cannot reproduce, on a system you must not break further.' },
  { id:'technical-design-docs', name:'Design Documents', tier:5, req:['architecture','technical-writing'],
    desc:'Write the proposal that gets a hard change agreed before anyone writes code.' },
  { id:'legacy-systems', name:'Working With Legacy Systems', tier:5, req:['code-reading','refactoring','risk-assessment'],
    desc:'Change something old, undocumented and load-bearing without an outage.' },
]);

addSkills({ cat: 'tech', group: 'Product & Delivery' }, [
  { id:'requirements', name:'Gathering Requirements', tier:4, req:['interviewing','technical-writing'],
    desc:'Find out what is actually needed, as distinct from what was asked for.' },
  { id:'agile-practice', name:'Iterative Delivery', tier:4, req:['project-planning','estimating-work'],
    desc:'Small increments, real feedback, and ceremonies that earn their time.' },
  { id:'product-thinking', name:'Product Thinking', tier:5, req:['requirements','ux-design','experimentation'],
    desc:'Decide what to build and what to refuse, based on evidence about users.' },
  { id:'technical-debt', name:'Managing Technical Debt', tier:5, req:['refactoring','stakeholders'],
    desc:'Make the cost visible to non-engineers and get it paid down deliberately.' },
  { id:'release-management', name:'Shipping Safely', tier:5, req:['cicd','observability'],
    desc:'Feature flags, canaries and rollbacks so releasing is not an event.' },
]);

addSkills({ cat: 'tech', group: 'Frontiers' }, [
  { id:'blockchain-literacy', name:'Blockchain Literacy', tier:4, req:['encryption-literacy','databases'],
    desc:'What a distributed ledger actually solves, and the many cases where it does not.' },
  { id:'quantum-computing', name:'Quantum Computing Literacy', tier:5, req:['linear-algebra','quantum-literacy'],
    desc:'Qubits, superposition and the small set of problems this would change.' },
  { id:'ar-vr', name:'Spatial Computing', tier:5, req:['game-dev','ux-design'],
    desc:'Build for headsets: presence, comfort and interfaces without a mouse.' },
  { id:'edge-computing', name:'Embedded & Edge Systems', tier:5, req:['microcontrollers','systems-programming'],
    desc:'Constrained memory, power budgets and code that must run for years unattended.' },
  { id:'digital-preservation', name:'Digital Preservation', tier:5, req:['backup-strategy','file-org','data-governance'],
    desc:'Formats, migration and metadata so your archive is readable in thirty years.' },
]);

addSkills({ cat: 'tech', group: 'Making Media' }, [
  { id:'screen-recording', name:'Screen Recording & Demos', tier:3, req:['computer-literacy','explaining'],
    desc:'Record a clear walkthrough so you never explain the same thing twice.' },
  { id:'podcasting', name:'Podcasting', tier:4, req:['sound-recording','interviewing','mixing'],
    desc:'Record, edit and publish audio people will listen to for forty minutes.' },
  { id:'newsletter', name:'Running a Newsletter', tier:4, req:['writing-practice','email-marketing'],
    desc:'Publish on a schedule to a list that stays subscribed.' },
  { id:'personal-site', name:'Building a Personal Site', tier:3, req:['html-css','portfolio'],
    desc:'Own your corner of the web instead of renting it from a platform.' },
  { id:'digital-archiving', name:'Archiving Your Own Life', tier:3, req:['backup-strategy','family-photos'],
    desc:'Photos, messages and documents preserved in formats that outlive the app.' },
]);

addSkills({ cat: 'tech', group: 'Digital Wellbeing' }, [
  { id:'notification-control', name:'Controlling Notifications', tier:1,
    desc:'Turn nearly all of them off; decide when to check rather than being told.' },
  { id:'screen-time', name:'Managing Screen Time', tier:2, req:['notification-control','habits'],
    desc:'Measure it honestly, then change the environment rather than relying on intent.' },
  { id:'algorithm-awareness', name:'Understanding Feeds', tier:3, req:['info-filtering','misinformation'],
    desc:'Know what is being optimised for and that it is not your interests.' },
  { id:'online-disagreement', name:'Arguing Online', tier:4, req:['online-community','steelmanning'],
    desc:'Engage without escalating, and recognise the threads worth leaving alone.' },
  { id:'digital-legacy', name:'Digital Legacy', tier:4, req:['password-hygiene','wills'],
    desc:'Accounts, photos and access arranged for the people who outlive you.' },
]);

addSkills({ cat: 'tech', group: 'Data & Numbers at Work' }, [
  { id:'chart-making', name:'Making a Chart', tier:3, req:['spreadsheets','visual-literacy'],
    desc:'Pick the chart the data wants and label it so nobody has to ask.' },
  { id:'dashboards', name:'Building a Dashboard', tier:4, req:['chart-making','business-metrics'],
    desc:'A handful of numbers, updated automatically, that someone actually looks at.' },
  { id:'data-storytelling', name:'Presenting Data', tier:4, req:['data-viz','presentations'],
    desc:'Lead with the finding, show the evidence, and state what should change.' },
  { id:'spreadsheet-hygiene', name:'Spreadsheet Hygiene', tier:3, req:['spreadsheets','file-org'],
    desc:'One row per record, no merged cells, and formulas someone else can audit.' },
  { id:'data-collection', name:'Collecting Data Well', tier:4, req:['survey-design','spreadsheet-hygiene'],
    desc:'Design the form so the analysis is possible before anyone fills it in.' },
]);

addSkills({ cat: 'tech', group: 'Technology & Society' }, [
  { id:'tech-ethics', name:'Ethics of What You Build', tier:5, req:['ai-ethics','professional-ethics'],
    desc:'Ask who could be harmed by this working exactly as intended.' },
  { id:'platform-literacy', name:'Understanding Platforms', tier:4, req:['algorithm-awareness','economics-literacy'],
    desc:'Network effects, lock-in and why the product changed without asking you.' },
  { id:'digital-inclusion', name:'Digital Inclusion', tier:4, req:['accessibility-tools','help-desk'],
    desc:'Help people offline or excluded get online, safely and on their own terms.' },
  { id:'open-source-use', name:'Using & Contributing to Open Source', tier:4, req:['version-control','code-review'],
    desc:'Report a bug well, send a small patch, and read the contributing guide first.' },
  { id:'tech-policy', name:'Technology Policy', tier:5, req:['platform-literacy','policy-reading'],
    desc:'Regulation of data, competition and AI, understood well enough to argue about.' },
]);
